<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Multivariate methods | Quantitative Methods for Geographers</title>
  <meta name="description" content="This is the script of the course ‘Quantitative Methods for Geographers’ run at the Geography Department of Humboldt-Universität zu Berlin." />
  <meta name="generator" content="bookdown 0.30 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Multivariate methods | Quantitative Methods for Geographers" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the script of the course ‘Quantitative Methods for Geographers’ run at the Geography Department of Humboldt-Universität zu Berlin." />
  <meta name="github-repo" content="krueger-t/qm4g" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Multivariate methods | Quantitative Methods for Geographers" />
  
  <meta name="twitter:description" content="This is the script of the course ‘Quantitative Methods for Geographers’ run at the Geography Department of Humboldt-Universität zu Berlin." />
  

<meta name="author" content="Tobias Krueger" />


<meta name="date" content="2024-10-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="07-glms.html"/>
<link rel="next" href="09-solutions.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>
<script src="libs/htmlwidgets/htmlwidgets.js"></script>
<script src="libs/rglWebGL-binding/rglWebGL.js"></script>
<link href="libs/rglwidgetClass/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass/rglClass.src.js"></script>
<script src="libs/rglwidgetClass/utils.src.js"></script>
<script src="libs/rglwidgetClass/buffer.src.js"></script>
<script src="libs/rglwidgetClass/subscenes.src.js"></script>
<script src="libs/rglwidgetClass/shaders.src.js"></script>
<script src="libs/rglwidgetClass/textures.src.js"></script>
<script src="libs/rglwidgetClass/projection.src.js"></script>
<script src="libs/rglwidgetClass/mouse.src.js"></script>
<script src="libs/rglwidgetClass/init.src.js"></script>
<script src="libs/rglwidgetClass/pieces.src.js"></script>
<script src="libs/rglwidgetClass/draw.src.js"></script>
<script src="libs/rglwidgetClass/controls.src.js"></script>
<script src="libs/rglwidgetClass/selection.src.js"></script>
<script src="libs/rglwidgetClass/rglTimer.src.js"></script>
<script src="libs/rglwidgetClass/pretty.src.js"></script>
<script src="libs/rglwidgetClass/axes.src.js"></script>
<script src="libs/rglwidgetClass/animation.src.js"></script>
<!--html_preserve--><script type = "text/plain" id = "rgl-vertex-shader">
#line 2 1
// File 1 is the vertex shader
#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#endif

attribute vec3 aPos;
attribute vec4 aCol;
uniform mat4 mvMatrix;
uniform mat4 prMatrix;
varying vec4 vCol;
varying vec4 vPosition;

#ifdef NEEDS_VNORMAL
attribute vec3 aNorm;
uniform mat4 normMatrix;
varying vec4 vNormal;
#endif

#if defined(HAS_TEXTURE) || defined (IS_TEXT)
attribute vec2 aTexcoord;
varying vec2 vTexcoord;
#endif

#ifdef FIXED_SIZE
uniform vec3 textScale;
#endif

#ifdef FIXED_QUADS
attribute vec3 aOfs;
#endif

#ifdef IS_TWOSIDED
#ifdef HAS_NORMALS
varying float normz;
uniform mat4 invPrMatrix;
#else
attribute vec3 aPos1;
attribute vec3 aPos2;
varying float normz;
#endif
#endif // IS_TWOSIDED

#ifdef FAT_LINES
attribute vec3 aNext;
attribute vec2 aPoint;
varying vec2 vPoint;
varying float vLength;
uniform float uAspect;
uniform float uLwd;
#endif


void main(void) {
  
#ifndef IS_BRUSH
#if defined(NCLIPPLANES) || !defined(FIXED_QUADS) || defined(HAS_FOG)
  vPosition = mvMatrix * vec4(aPos, 1.);
#endif
  
#ifndef FIXED_QUADS
  gl_Position = prMatrix * vPosition;
#endif
#endif // !IS_BRUSH
  
#ifdef IS_POINTS
  gl_PointSize = POINTSIZE;
#endif
  
  vCol = aCol;
  
#ifdef NEEDS_VNORMAL
  vNormal = normMatrix * vec4(-aNorm, dot(aNorm, aPos));
#endif
  
#ifdef IS_TWOSIDED
#ifdef HAS_NORMALS
  /* normz should be calculated *after* projection */
  normz = (invPrMatrix*vNormal).z;
#else
  vec4 pos1 = prMatrix*(mvMatrix*vec4(aPos1, 1.));
  pos1 = pos1/pos1.w - gl_Position/gl_Position.w;
  vec4 pos2 = prMatrix*(mvMatrix*vec4(aPos2, 1.));
  pos2 = pos2/pos2.w - gl_Position/gl_Position.w;
  normz = pos1.x*pos2.y - pos1.y*pos2.x;
#endif
#endif // IS_TWOSIDED
  
#ifdef NEEDS_VNORMAL
  vNormal = vec4(normalize(vNormal.xyz/vNormal.w), 1);
#endif
  
#if defined(HAS_TEXTURE) || defined(IS_TEXT)
  vTexcoord = aTexcoord;
#endif
  
#if defined(FIXED_SIZE) && !defined(ROTATING)
  vec4 pos = prMatrix * mvMatrix * vec4(aPos, 1.);
  pos = pos/pos.w;
  gl_Position = pos + vec4(aOfs*textScale, 0.);
#endif
  
#if defined(IS_SPRITES) && !defined(FIXED_SIZE)
  vec4 pos = mvMatrix * vec4(aPos, 1.);
  pos = pos/pos.w + vec4(aOfs,  0.);
  gl_Position = prMatrix*pos;
#endif
  
#ifdef FAT_LINES
  /* This code was inspired by Matt Deslauriers' code in 
   https://mattdesl.svbtle.com/drawing-lines-is-hard */
  vec2 aspectVec = vec2(uAspect, 1.0);
  mat4 projViewModel = prMatrix * mvMatrix;
  vec4 currentProjected = projViewModel * vec4(aPos, 1.0);
  currentProjected = currentProjected/currentProjected.w;
  vec4 nextProjected = projViewModel * vec4(aNext, 1.0);
  vec2 currentScreen = currentProjected.xy * aspectVec;
  vec2 nextScreen = (nextProjected.xy / nextProjected.w) * aspectVec;
  float len = uLwd;
  vec2 dir = vec2(1.0, 0.0);
  vPoint = aPoint;
  vLength = length(nextScreen - currentScreen)/2.0;
  vLength = vLength/(vLength + len);
  if (vLength > 0.0) {
    dir = normalize(nextScreen - currentScreen);
  }
  vec2 normal = vec2(-dir.y, dir.x);
  dir.x /= uAspect;
  normal.x /= uAspect;
  vec4 offset = vec4(len*(normal*aPoint.x*aPoint.y - dir), 0.0, 0.0);
  gl_Position = currentProjected + offset;
#endif
  
#ifdef IS_BRUSH
  gl_Position = vec4(aPos, 1.);
#endif
}
</script>
<script type = "text/plain" id = "rgl-fragment-shader">
#line 2 2
// File 2 is the fragment shader
#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#endif
varying vec4 vCol; // carries alpha
varying vec4 vPosition;
#if defined(HAS_TEXTURE) || defined (IS_TEXT)
varying vec2 vTexcoord;
uniform sampler2D uSampler;
#endif

#ifdef HAS_FOG
uniform int uFogMode;
uniform vec3 uFogColor;
uniform vec4 uFogParms;
#endif

#if defined(IS_LIT) && !defined(FIXED_QUADS)
varying vec4 vNormal;
#endif

#if NCLIPPLANES > 0
uniform vec4 vClipplane[NCLIPPLANES];
#endif

#if NLIGHTS > 0
uniform mat4 mvMatrix;
#endif

#ifdef IS_LIT
uniform vec3 emission;
uniform float shininess;
#if NLIGHTS > 0
uniform vec3 ambient[NLIGHTS];
uniform vec3 specular[NLIGHTS]; // light*material
uniform vec3 diffuse[NLIGHTS];
uniform vec3 lightDir[NLIGHTS];
uniform bool viewpoint[NLIGHTS];
uniform bool finite[NLIGHTS];
#endif
#endif // IS_LIT

#ifdef IS_TWOSIDED
uniform bool front;
varying float normz;
#endif

#ifdef FAT_LINES
varying vec2 vPoint;
varying float vLength;
#endif

void main(void) {
  vec4 fragColor;
#ifdef FAT_LINES
  vec2 point = vPoint;
  bool neg = point.y < 0.0;
  point.y = neg ? (point.y + vLength)/(1.0 - vLength) :
                 -(point.y - vLength)/(1.0 - vLength);
#if defined(IS_TRANSPARENT) && defined(IS_LINESTRIP)
  if (neg && length(point) <= 1.0) discard;
#endif
  point.y = min(point.y, 0.0);
  if (length(point) > 1.0) discard;
#endif // FAT_LINES
  
#ifdef ROUND_POINTS
  vec2 coord = gl_PointCoord - vec2(0.5);
  if (length(coord) > 0.5) discard;
#endif
  
#if NCLIPPLANES > 0
  for (int i = 0; i < NCLIPPLANES; i++)
    if (dot(vPosition, vClipplane[i]) < 0.0) discard;
#endif
    
#ifdef FIXED_QUADS
    vec3 n = vec3(0., 0., 1.);
#elif defined(IS_LIT)
    vec3 n = normalize(vNormal.xyz);
#endif
    
#ifdef IS_TWOSIDED
    if ((normz <= 0.) != front) discard;
#endif
    
#ifdef IS_LIT
    vec3 eye = normalize(-vPosition.xyz/vPosition.w);
    vec3 lightdir;
    vec4 colDiff;
    vec3 halfVec;
    vec4 lighteffect = vec4(emission, 0.);
    vec3 col;
    float nDotL;
#ifdef FIXED_QUADS
    n = -faceforward(n, n, eye);
#endif
    
#if NLIGHTS > 0
    for (int i=0;i<NLIGHTS;i++) {
      colDiff = vec4(vCol.rgb * diffuse[i], vCol.a);
      lightdir = lightDir[i];
      if (!viewpoint[i])
        lightdir = (mvMatrix * vec4(lightdir, 1.)).xyz;
      if (!finite[i]) {
        halfVec = normalize(lightdir + eye);
      } else {
        lightdir = normalize(lightdir - vPosition.xyz/vPosition.w);
        halfVec = normalize(lightdir + eye);
      }
      col = ambient[i];
      nDotL = dot(n, lightdir);
      col = col + max(nDotL, 0.) * colDiff.rgb;
      col = col + pow(max(dot(halfVec, n), 0.), shininess) * specular[i];
      lighteffect = lighteffect + vec4(col, colDiff.a);
    }
#endif
    
#else // not IS_LIT
    vec4 colDiff = vCol;
    vec4 lighteffect = colDiff;
#endif
    
#ifdef IS_TEXT
    vec4 textureColor = lighteffect*texture2D(uSampler, vTexcoord);
#endif
    
#ifdef HAS_TEXTURE
#ifdef TEXTURE_rgb
    vec4 textureColor = lighteffect*vec4(texture2D(uSampler, vTexcoord).rgb, 1.);
#endif
    
#ifdef TEXTURE_rgba
    vec4 textureColor = lighteffect*texture2D(uSampler, vTexcoord);
#endif
    
#ifdef TEXTURE_alpha
    vec4 textureColor = texture2D(uSampler, vTexcoord);
    float luminance = dot(vec3(1.,1.,1.), textureColor.rgb)/3.;
    textureColor =  vec4(lighteffect.rgb, lighteffect.a*luminance);
#endif
    
#ifdef TEXTURE_luminance
    vec4 textureColor = vec4(lighteffect.rgb*dot(texture2D(uSampler, vTexcoord).rgb, vec3(1.,1.,1.))/3., lighteffect.a);
#endif
    
#ifdef TEXTURE_luminance_alpha
    vec4 textureColor = texture2D(uSampler, vTexcoord);
    float luminance = dot(vec3(1.,1.,1.),textureColor.rgb)/3.;
    textureColor = vec4(lighteffect.rgb*luminance, lighteffect.a*textureColor.a);
#endif
    
    fragColor = textureColor;

#elif defined(IS_TEXT)
    if (textureColor.a < 0.1)
      discard;
    else
      fragColor = textureColor;
#else
    fragColor = lighteffect;
#endif // HAS_TEXTURE
    
#ifdef HAS_FOG
    // uFogParms elements: x = near, y = far, z = fogscale, w = (1-sin(FOV/2))/(1+sin(FOV/2))
    // In Exp and Exp2: use density = density/far
    // fogF will be the proportion of fog
    // Initialize it to the linear value
    float fogF;
    if (uFogMode > 0) {
      fogF = (uFogParms.y - vPosition.z/vPosition.w)/(uFogParms.y - uFogParms.x);
      if (uFogMode > 1)
        fogF = mix(uFogParms.w, 1.0, fogF);
      fogF = fogF*uFogParms.z;
      if (uFogMode == 2)
        fogF = 1.0 - exp(-fogF);
      // Docs are wrong: use (density*c)^2, not density*c^2
      // https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/src/mesa/swrast/s_fog.c#L58
      else if (uFogMode == 3)
        fogF = 1.0 - exp(-fogF*fogF);
      fogF = clamp(fogF, 0.0, 1.0);
      gl_FragColor = vec4(mix(fragColor.rgb, uFogColor, fogF), fragColor.a);
    } else gl_FragColor = fragColor;
#else
    gl_FragColor = fragColor;
#endif // HAS_FOG
    
}
</script><!--/html_preserve-->
<script src="libs/CanvasMatrix4/CanvasMatrix.src.js"></script>
<script src="libs/kePrint/kePrint.js"></script>
<link href="libs/lightable/lightable.css" rel="stylesheet" />
<link href="libs/bsTable/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Methods for Geographers</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="02-math.html"><a href="02-math.html"><i class="fa fa-check"></i><b>1</b> Mathematical preliminaries</a></li>
<li class="chapter" data-level="2" data-path="03-lin_reg.html"><a href="03-lin_reg.html"><i class="fa fa-check"></i><b>2</b> Linear regression</a></li>
<li class="chapter" data-level="3" data-path="04-categorical_vars.html"><a href="04-categorical_vars.html"><i class="fa fa-check"></i><b>3</b> Categorical predictors</a></li>
<li class="chapter" data-level="4" data-path="05-multiple_lin_reg.html"><a href="05-multiple_lin_reg.html"><i class="fa fa-check"></i><b>4</b> Multiple linear regression</a></li>
<li class="chapter" data-level="5" data-path="06-ml_bayes.html"><a href="06-ml_bayes.html"><i class="fa fa-check"></i><b>5</b> Probabilistic underpinnings</a></li>
<li class="chapter" data-level="6" data-path="07-glms.html"><a href="07-glms.html"><i class="fa fa-check"></i><b>6</b> Generalised Linear Models (GLMs)</a></li>
<li class="chapter" data-level="7" data-path="08-multivariate.html"><a href="08-multivariate.html"><i class="fa fa-check"></i><b>7</b> Multivariate methods</a></li>
<li class="chapter" data-level="" data-path="09-solutions.html"><a href="09-solutions.html"><i class="fa fa-check"></i>Solutions to exercises</a></li>
<li class="chapter" data-level="" data-path="10-refs.html"><a href="10-refs.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantitative Methods for Geographers</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multivariate" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Multivariate methods<a href="08-multivariate.html#multivariate" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Multivariate regression</strong> extends the case of multiple regression (one response variable/ multiple predictor variables) to the case of <em>multiple response variables</em>/ multiple predictor variables. <em>Predictors are continuous variables</em>, though there is the same correspondence as between linear regression and ANOVA.</p>
<p><strong>Multivariate analysis of variance (MANOVA)</strong> (Chapter <a href="08-multivariate.html#manova">7.3</a>) extends the case of ANOVA (one response variable/ multiple predictor variables) to the case of <em>multiple response variables</em>/ multiple predictor variables. <em>Predictors are categorical variables</em>, though MANOVA relates to multivariate regression just like ANOVA does to linear regression.</p>
<p><strong>Discriminant Function Analysis (DFA)</strong> (Chapter <a href="08-multivariate.html#dfa">7.4</a>) is a <em>classification</em> method that tests how well multi-response observations discriminate between pre-determined groups, and can also be used to classify new observations into one of the groups.</p>
<p><strong>Principle Component Analysis (PCA)</strong> (Chapter <a href="08-multivariate.html#pca">7.2</a>), <strong>Factor Analysis (FA)</strong> and related methods aim at finding <em>structure</em> in a multivariate dataset, not deciding on response/predictor variables just yet. They extract a reduced set of components that explain much of the <em>variability</em> or <em>correlation</em> among the original variables. PCA and FA are typically employed to pre-structure and <em>simplify</em> a problem by reducing its data dimensions, e.g. to reduce collinearity (compare Chapter <a href="05-multiple_lin_reg.html#multiplelinreg">4</a>).</p>
<p><strong>Cluster Analysis</strong> (Chapter <a href="08-multivariate.html#clusteranalysis">7.1</a>) looks for groups in a multivariate dataset. Data points belonging to the same group “resemble” each other - we will see what this means. Data points belonging to different groups are “dissimilar”.</p>
<div id="clusteranalysis" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Cluster analysis<a href="08-multivariate.html#clusteranalysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This section is based on material by Cornelius Senf.<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a> Cluster analysis looks for groups (clusters) in a multivariate dataset. Objects (data points) belonging to the same group “resemble” each other. Objects belonging to different groups are “dissimilar”. There are three groups of methods:</p>
<ol style="list-style-type: decimal">
<li><strong>Partitioning</strong> the dataset into a number of clusters specified by the user, e.g. the <em>kmeans</em> algorithm</li>
<li><strong>Hierarchical</strong>, starting with each object (data point) as a separate cluster and then aggregating these step by step, ending up with a single cluster</li>
<li><strong>Divisive</strong>, starting with a single cluster of all objects (data points) and then splitting this step by step until all objects are in different clusters</li>
</ol>
<p>Let us illustrate the principles of these methods with the <em>Iris</em> dataset that is available from <em>R</em>, on which cluster analysis can be used to separate taxonomic groups. The dataset consists of a sample of <em>Iris</em> flowers for which the lengths and widths of their sepals and petals were measured. Sepals and petals are two different kinds of leaves in the flower. The question is: <em>Can we separate clusters of flowers that are sufficiently different with respect to these four features?</em> This then could form the basis of deriving taxonomic groups; indeed this is a typical approach in botany. To get a sense of the dataset let us first plot a scatterplot matrix:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="08-multivariate.html#cb149-1" tabindex="-1"></a><span class="co"># load Iris dataset</span></span>
<span id="cb149-2"><a href="08-multivariate.html#cb149-2" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb149-3"><a href="08-multivariate.html#cb149-3" tabindex="-1"></a><span class="co"># scatterplot matrix</span></span>
<span id="cb149-4"><a href="08-multivariate.html#cb149-4" tabindex="-1"></a><span class="fu">plot</span>(iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-38-1.png" width="80%" /></p>
<p>We can already see at least two clusters. In some dimensions (petal length and width) they are more apart than in others (sepal length and width). Let us formalise this analysis using the <em>kmeans</em> algorithm and afterwards look briefly at what hierarchical methods do.</p>
<div id="the-kmeans-algorithm" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> The <em>kmeans</em> algorithm<a href="08-multivariate.html#the-kmeans-algorithm" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The purpose of <em>kmeans</em> is to build clusters such that the distance of cluster objects (data points) to cluster <em>centroids</em> (vectors of means) is minimised. The algorithm proceeds though the following steps:</p>
<ol style="list-style-type: decimal">
<li>Choose <span class="math inline">\(k\)</span> random cluster centroids in the multivariate space</li>
<li>Allocate each object to a cluster so that <em>total intra-cluster sum of squares</em> (Equation <a href="08-multivariate.html#eq:intraclusterss">(7.1)</a>) is minimised</li>
</ol>
<p><span class="math display" id="eq:intraclusterss">\[\begin{equation}
\sum_{j=1}^{k}\sum_{i=1}^{n_j}\lVert \mathbf{y}_{ij}-\boldsymbol{\mu}_j\rVert^2
\tag{7.1}
\end{equation}\]</span></p>
<p><span class="math inline">\(\boldsymbol{\mu}_j\)</span> is the centroid of cluster <span class="math inline">\(j=1,2,\ldots,k\)</span>, i.e. the vector of means across the data dimensions (here four). <span class="math inline">\(\mathbf{y}_{ij}\)</span> is data point <span class="math inline">\(i=1,2,\ldots,n_j\)</span> of cluster <span class="math inline">\(j\)</span>, i.e. a multivariate vector, too. <span class="math inline">\(\lVert\cdot\rVert\)</span> symbolises the <em>Euclidean distance</em>.</p>
<ol start="3" style="list-style-type: decimal">
<li>Re-calculate cluster centroids</li>
<li>Repeat steps 2-3 until cluster centroids are not changing much anymore (by some chosen criterion)</li>
</ol>
<p>Often the Euclidean distance is used as a measure of (dis)similarity but others can be specified as well.</p>
<p>We have to tell the algorithm how many clusters we want. Let us use two to begin with (because that was our intuition earlier):</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="08-multivariate.html#cb150-1" tabindex="-1"></a><span class="co"># run kmeans algorithm on Iris data asking for 2 clusters</span></span>
<span id="cb150-2"><a href="08-multivariate.html#cb150-2" tabindex="-1"></a>iris_fit2 <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">centers=</span><span class="dv">2</span>)</span>
<span id="cb150-3"><a href="08-multivariate.html#cb150-3" tabindex="-1"></a><span class="co"># scatterplot matrix</span></span>
<span id="cb150-4"><a href="08-multivariate.html#cb150-4" tabindex="-1"></a><span class="fu">plot</span>(iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">col=</span>iris_fit2<span class="sc">$</span>cluster)</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-39-1.png" width="80%" /></p>
<p>Two clusters did not seem enough to reproduce the separation we see visually. Let us increase the number of clusters to three:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="08-multivariate.html#cb151-1" tabindex="-1"></a><span class="co"># run kmeans algorithm on Iris data asking for 3 clusters</span></span>
<span id="cb151-2"><a href="08-multivariate.html#cb151-2" tabindex="-1"></a>iris_fit3 <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">centers=</span><span class="dv">3</span>)</span>
<span id="cb151-3"><a href="08-multivariate.html#cb151-3" tabindex="-1"></a><span class="co"># scatterplot matrix</span></span>
<span id="cb151-4"><a href="08-multivariate.html#cb151-4" tabindex="-1"></a><span class="fu">plot</span>(iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">col=</span>iris_fit3<span class="sc">$</span>cluster)</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-40-1.png" width="80%" /></p>
<p>I think we would be happy with this visually. But are there perhaps even more clusters? When to stop? A useful stopping criterion is to look at the inflexion point where the total intra-cluster sum of squares (Equation <a href="08-multivariate.html#eq:intraclusterss">(7.1)</a>) does not change much anymore with increasing <span class="math inline">\(k\)</span> in a so called <strong>screeplot</strong><a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a>:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="08-multivariate.html#cb152-1" tabindex="-1"></a><span class="co"># specify vector of clusters</span></span>
<span id="cb152-2"><a href="08-multivariate.html#cb152-2" tabindex="-1"></a>clusters <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb152-3"><a href="08-multivariate.html#cb152-3" tabindex="-1"></a><span class="co"># initialise corresponding vector of total intra-cluster sum of squares</span></span>
<span id="cb152-4"><a href="08-multivariate.html#cb152-4" tabindex="-1"></a>ticss <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">10</span>)</span>
<span id="cb152-5"><a href="08-multivariate.html#cb152-5" tabindex="-1"></a><span class="co"># loop through vector of clusters</span></span>
<span id="cb152-6"><a href="08-multivariate.html#cb152-6" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> clusters){</span>
<span id="cb152-7"><a href="08-multivariate.html#cb152-7" tabindex="-1"></a>  <span class="co"># run kmeans</span></span>
<span id="cb152-8"><a href="08-multivariate.html#cb152-8" tabindex="-1"></a>  iris_fit <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">centers=</span>i)</span>
<span id="cb152-9"><a href="08-multivariate.html#cb152-9" tabindex="-1"></a>  <span class="co"># collect total intra-cluster sum of squares</span></span>
<span id="cb152-10"><a href="08-multivariate.html#cb152-10" tabindex="-1"></a>  ticss[i] <span class="ot">&lt;-</span> iris_fit<span class="sc">$</span>tot.withinss</span>
<span id="cb152-11"><a href="08-multivariate.html#cb152-11" tabindex="-1"></a>}</span>
<span id="cb152-12"><a href="08-multivariate.html#cb152-12" tabindex="-1"></a><span class="co"># plot total intra-cluster sum of squares against clusters</span></span>
<span id="cb152-13"><a href="08-multivariate.html#cb152-13" tabindex="-1"></a><span class="fu">plot</span>(clusters, ticss, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">type =</span> <span class="st">&#39;b&#39;</span>, <span class="at">xlab =</span> <span class="st">&quot;Number of clusters&quot;</span>,</span>
<span id="cb152-14"><a href="08-multivariate.html#cb152-14" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Total intra-cluster sum of squares&quot;</span>)</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-41-1.png" width="80%" /></p>
<p>We can see that beyond three clusters the improvement in separation is minimal, so we would leave it at three. This, it turns out, matches almost perfectly the official taxonomic separation of the <em>Iris</em> dataset:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="08-multivariate.html#cb153-1" tabindex="-1"></a><span class="co"># contingency table of cluster:species matches</span></span>
<span id="cb153-2"><a href="08-multivariate.html#cb153-2" tabindex="-1"></a><span class="fu">table</span>(iris_fit3<span class="sc">$</span>cluster, iris<span class="sc">$</span>Species)</span></code></pre></div>
<pre><code>##    
##     setosa versicolor virginica
##   1      0          2        36
##   2      0         48        14
##   3     50          0         0</code></pre>
<p>The separation of <em>Iris versicolor</em> and <em>Iris virginica</em>, however, is not perfect.</p>
</div>
<div id="hierarchical-methods" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Hierarchical methods<a href="08-multivariate.html#hierarchical-methods" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The principle of hierarchical methods is to start with each object as a separate cluster and then aggregate these step by step, ending up with a single cluster. Note, devisive methods are not covered here, but they work exactly the other way round. An example algorithm works as follows:</p>
<ol style="list-style-type: decimal">
<li>Build <em>dissimilarity matrix</em>, i.e. a matrix of the distances of every object to every other object in the multivariate space, e.g. by Euclidean distance <span class="math inline">\(\lVert\mathbf{y}_i-\mathbf{y}_{i^*}\rVert\)</span></li>
<li>Start with each object as a separate cluster</li>
<li>Join the two most similar clusters, e.g. those that lead to minimum increase in total intra-cluster sum of squares after merging (Equation <a href="08-multivariate.html#eq:intraclusterss">(7.1)</a>); this is called <em>Ward’s method</em></li>
<li>Repeat step 3 until a single cluster is built</li>
</ol>
<p>The result is a <strong>dendrogram</strong>, whose “height” is the distance between clusters, e.g. in Ward’s method the increase in the intra-cluster sum of squares of the clusters being merged:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="08-multivariate.html#cb155-1" tabindex="-1"></a><span class="co"># construct dissimilarity matrix for Iris data</span></span>
<span id="cb155-2"><a href="08-multivariate.html#cb155-2" tabindex="-1"></a>iris_dist <span class="ot">&lt;-</span> <span class="fu">dist</span>(iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span>
<span id="cb155-3"><a href="08-multivariate.html#cb155-3" tabindex="-1"></a><span class="co"># run hierarchical clustering with Ward&#39;s method</span></span>
<span id="cb155-4"><a href="08-multivariate.html#cb155-4" tabindex="-1"></a>iris_fith <span class="ot">&lt;-</span> <span class="fu">hclust</span>(iris_dist, <span class="at">method=</span><span class="st">&quot;ward.D2&quot;</span>)</span>
<span id="cb155-5"><a href="08-multivariate.html#cb155-5" tabindex="-1"></a><span class="co"># dendrogram</span></span>
<span id="cb155-6"><a href="08-multivariate.html#cb155-6" tabindex="-1"></a><span class="fu">plot</span>(iris_fith)</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-43-1.png" width="80%" /></p>
<p>Again we can see the three clearly separate clusters, beyond which any further separation is ambiguous.</p>
</div>
</div>
<div id="pca" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Principal Component Analysis (PCA)<a href="08-multivariate.html#pca" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To illustrate PCA, I will use a dataset from <span class="citation">Lovett, Weathers, and Sobczak (<a href="#ref-lovett2000">2000</a>)</span>, cited in <span class="citation">Quinn and Keough (<a href="#ref-quinn2002">2002</a>)</span>, that consists of stream chemistry measurements from 38 forested catchments in the Catskill Mountains, New York:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="08-multivariate.html#cb156-1" tabindex="-1"></a><span class="co"># load stream chemistry data</span></span>
<span id="cb156-2"><a href="08-multivariate.html#cb156-2" tabindex="-1"></a>streams <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/streams.txt&quot;</span>,<span class="at">header=</span>T)</span>
<span id="cb156-3"><a href="08-multivariate.html#cb156-3" tabindex="-1"></a><span class="fu">head</span>(streams)</span></code></pre></div>
<pre><code>##    catchm_name max_elev sample_elev stream_length
## 1   Santa_Cruz     1006         680          1680
## 2      Colgate     1216         628          3912
## 3       Halsey     1204         625          4032
## 4 Batavia_Hill     1213         663          3072
## 5 Windham_Ridg     1074         616          2520
## 6 Silver_Sprin     1113         451          3120
##   catchm_area  NO3 TON   TN NH4   DOC  SO4   CL   CA
## 1          23 24.2 5.6 29.9 0.8 180.4 50.6 15.5 54.7
## 2         462 25.4 4.9 30.3 1.4 108.8 55.4 16.4 58.4
## 3         297 29.7 4.4 33.0 0.8 104.7 56.5 17.1 65.9
## 4         399 22.1 6.1 28.3 1.4  84.5 57.5 16.8 59.5
## 5         207 13.1 5.7 17.6 0.6  82.4 58.3 18.3 54.6
## 6         348 27.5 3.0 30.8 1.1  86.6 63.0 15.7 68.5
##     MG    H
## 1 14.4 0.48
## 2 17.0 0.24
## 3 19.6 0.47
## 4 19.5 0.23
## 5 21.9 0.37
## 6 22.4 0.17</code></pre>
<p>The dataset first lists catchment characteristics: name, maximum elevation, elevation where stream water sample was taken, stream length, catchment area. The stream chemistry variables are concentrations of: nitrate, total organic nitrogen, total nitrogen, ammonium, dissolved organic carbon, sulfate, chloride, calcium, magnesium, hydrogen.</p>
<div id="from-univariate-normal-to-multivariate-normal" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> From univariate normal to multivariate normal<a href="08-multivariate.html#from-univariate-normal-to-multivariate-normal" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Like univariate methods, multivariate methods, too, rely on the normality assumption; the univariate normal distribution (Figure <a href="08-multivariate.html#fig:camg">7.1</a>, left) is generalised to the <strong>multivariate normal distribution</strong> (Figure <a href="08-multivariate.html#fig:camg">7.1</a>, right). Taking calcium concentration in the stream chemistry dataset as an example, the univariate normal model would be <span class="math inline">\(N(\mu,\sigma)\)</span> with mean <span class="math inline">\(\mu=65.13\)</span> and variance <span class="math inline">\(\sigma^2=194.74\)</span> (Figure <a href="08-multivariate.html#fig:camg">7.1</a>, left). Looking at calcium and magnesium concentration together, the multivariate normal model would be <span class="math inline">\(MVN(\boldsymbol\mu,\boldsymbol\Sigma)\)</span> with <strong>centroid</strong> (vector of means) <span class="math inline">\(\boldsymbol\mu=\begin{pmatrix}65.13&amp;22.86\end{pmatrix}^T\)</span> and <strong>variance-covariance matrix</strong> <span class="math inline">\(\boldsymbol\Sigma=\begin{pmatrix}194.74&amp;27.03\\27.03&amp;194.74\end{pmatrix}\)</span> (Figure <a href="08-multivariate.html#fig:camg">7.1</a>, right).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:camg"></span>
<img src="figs/ca_pdf.jpg" alt="Left: Histogram of calcium concentration measurements from stream chemistry dataset, with fitted normal distribution. The vertical line marks the mean. Right: Scatterplot of calcium against magnesium concentration measurements, with coloured countours of fitted multivariate normal distribution. The vertical and horizontal lines are the individual means, which intersect at the centroid. Data from: @lovett2000, cited in @quinn2002." width="50%" /><img src="figs/ca_mg_jointpdf.jpg" alt="Left: Histogram of calcium concentration measurements from stream chemistry dataset, with fitted normal distribution. The vertical line marks the mean. Right: Scatterplot of calcium against magnesium concentration measurements, with coloured countours of fitted multivariate normal distribution. The vertical and horizontal lines are the individual means, which intersect at the centroid. Data from: @lovett2000, cited in @quinn2002." width="50%" />
<p class="caption">
Figure 7.1: Left: Histogram of calcium concentration measurements from stream chemistry dataset, with fitted normal distribution. The vertical line marks the mean. Right: Scatterplot of calcium against magnesium concentration measurements, with coloured countours of fitted multivariate normal distribution. The vertical and horizontal lines are the individual means, which intersect at the centroid. Data from: <span class="citation">Lovett, Weathers, and Sobczak (<a href="#ref-lovett2000">2000</a>)</span>, cited in <span class="citation">Quinn and Keough (<a href="#ref-quinn2002">2002</a>)</span>.
</p>
</div>
<p>The <strong>variance-covariance matrix</strong> (or just covariance matrix) is a matrix of associations between variables. On its diagonal are the variances of the individual variables,<a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a> on the off-diagonals are the covariances between two variables:</p>
<p><span class="math display" id="eq:covmatrix">\[\begin{equation}
\mathbf{C}=\begin{pmatrix}
\frac{\sum_{i=1}^{n}\left(y_{i1}-\bar y_1\right)^2}{n-1} &amp; \cdots &amp; \frac{\sum_{i=1}^{n}\left(y_{ip}-\bar y_p\right)\cdot\left(y_{i1}-\bar y_1\right)}{n-1} \\
\vdots &amp; \ddots &amp; \vdots \\
\frac{\sum_{i=1}^{n}\left(y_{i1}-\bar y_1\right)\cdot\left(y_{ip}-\bar y_p\right)}{n-1} &amp; \cdots &amp; \frac{\sum_{i=1}^{n}\left(y_{ip}-\bar y_p\right)^2}{n-1}
\end{pmatrix}
\tag{7.2}
\end{equation}\]</span></p>
<p>Normalising the variance-covariance terms in Equation <a href="08-multivariate.html#eq:covmatrix">(7.2)</a> by the variances of the respective variables, e.g. <span class="math inline">\(corr\left(y_1,y_2\right)=\frac{cov\left(y_1,y_2\right)}{\sqrt{\sigma_{y_1}^2\cdot\sigma_{y_2}^2}}=\frac{cov\left(y_1,y_2\right)}{\sigma_{y_1}\cdot\sigma_{y_2}}\)</span>, yields the <strong>correlation matrix</strong>:</p>
<p><span class="math display" id="eq:corrmatrix">\[\begin{equation}
\mathbf{R}=\begin{pmatrix}
\frac{\sum_{i=1}^{n}\left(y_{i1}-\bar y_1\right)^2}{\sqrt{\sum_{i=1}^{n}\left(y_{i1}-\bar y_1\right)^2\cdot\sum_{i=1}^{n}\left(y_{i1}-\bar y_1\right)^2}} &amp; \cdots &amp; \frac{\sum_{i=1}^{n}\left(y_{ip}-\bar y_p\right)\cdot\left(y_{i1}-\bar y_1\right)}{\sqrt{\sum_{i=1}^{n}\left(y_{ip}-\bar y_p\right)^2\cdot\sum_{i=1}^{n}\left(y_{i1}-\bar y_1\right)^2}} \\
\vdots &amp; \ddots &amp; \vdots \\
\frac{\sum_{i=1}^{n}\left(y_{i1}-\bar y_1\right)\cdot\left(y_{ip}-\bar y_p\right)}{\sqrt{\sum_{i=1}^{n}\left(y_{i1}-\bar y_1\right)^2\cdot\sum_{i=1}^{n}\left(y_{ip}-\bar y_p\right)^2}} &amp; \cdots &amp; \frac{\sum_{i=1}^{n}\left(y_{ip}-\bar y_p\right)^2}{\sqrt{\sum_{i=1}^{n}\left(y_{ip}-\bar y_p\right)^2\cdot\sum_{i=1}^{n}\left(y_{ip}-\bar y_p\right)^2}}
\end{pmatrix}
\tag{7.3}
\end{equation}\]</span></p>
<p>Correlations terms are between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span>. Let us look at the associations between the variables in the stream chemistry dataset:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="08-multivariate.html#cb158-1" tabindex="-1"></a><span class="fu">pairs</span>(streams[,<span class="dv">6</span><span class="sc">:</span><span class="dv">15</span>], <span class="at">diag.panel =</span> panel.hist)</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>First of all, we notice the non-normality of DOC, Cl and H (at least; in principle this diagnosis is ambiguous). Hence we log-transform these three variables to make them adhere better to normality:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="08-multivariate.html#cb159-1" tabindex="-1"></a>streams_log <span class="ot">&lt;-</span> streams</span>
<span id="cb159-2"><a href="08-multivariate.html#cb159-2" tabindex="-1"></a>streams_log<span class="sc">$</span>DOC <span class="ot">&lt;-</span> <span class="fu">log</span>(streams<span class="sc">$</span>DOC)</span>
<span id="cb159-3"><a href="08-multivariate.html#cb159-3" tabindex="-1"></a>streams_log<span class="sc">$</span>CL <span class="ot">&lt;-</span> <span class="fu">log</span>(streams<span class="sc">$</span>CL)</span>
<span id="cb159-4"><a href="08-multivariate.html#cb159-4" tabindex="-1"></a>streams_log<span class="sc">$</span>H <span class="ot">&lt;-</span> <span class="fu">log</span>(streams<span class="sc">$</span>H)</span>
<span id="cb159-5"><a href="08-multivariate.html#cb159-5" tabindex="-1"></a><span class="fu">pairs</span>(streams_log[,<span class="dv">6</span><span class="sc">:</span><span class="dv">15</span>], <span class="at">diag.panel =</span> panel.hist)</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>We then notice a positive correlation between NO3 and TN; most of the total nitrogen in streams actually comes in the form of nitrate. We notice a positive correlation between Ca and Mg; both are characteristic of alkaline waters and often appear together. We notice a positive correlation between Mg (and Ca) and SO4; magnesium (and calcium) often appear as Mg(Ca)-sulphate. And we notice a negative correlation between Ca and H; calcium is characteristic of alkaline waters, i.e. waters that have a high pH, hence a low hydrogen concentration. These associations are reflected in the covariance matrix:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="08-multivariate.html#cb160-1" tabindex="-1"></a><span class="fu">cov</span>(streams_log[,<span class="dv">6</span><span class="sc">:</span><span class="dv">15</span>])</span></code></pre></div>
<pre><code>##          NO3       TON      TN      NH4      DOC
## NO3  74.1885 -4.367084 68.5691 -1.21607  0.26400
## TON  -4.3671  1.636707 -2.5259  0.14817  0.07964
## TN   68.5691 -2.525910 65.6040 -0.97097  0.30097
## NH4  -1.2161  0.148165 -0.9710  0.53607 -0.09427
## DOC   0.2640  0.079635  0.3010 -0.09427  0.11367
## SO4  -1.8440  0.358563  0.9396  0.37102 -0.61138
## CL   -1.2917  0.060403 -1.1992  0.07313 -0.01936
## CA   29.1344 -2.879523 29.0208  0.57644 -1.25322
## MG  -14.7775  2.627397 -9.8612  0.77962 -0.60796
## H     0.3517 -0.008264  0.1717 -0.10161  0.09358
##         SO4       CL       CA       MG         H
## NO3 -1.8440 -1.29173  29.1344 -14.7775  0.351681
## TON  0.3586  0.06040  -2.8795   2.6274 -0.008264
## TN   0.9396 -1.19916  29.0208  -9.8612  0.171718
## NH4  0.3710  0.07313   0.5764   0.7796 -0.101607
## DOC -0.6114 -0.01936  -1.2532  -0.6080  0.093576
## SO4 27.2433  0.47721  35.0845  19.8258 -1.599979
## CL   0.4772  0.12766   0.8214   1.0110 -0.080456
## CA  35.0845  0.82144 194.7418  27.0328 -7.639475
## MG  19.8258  1.01104  27.0328  26.2495 -1.883364
## H   -1.6000 -0.08046  -7.6395  -1.8834  0.454193</code></pre>
<p>In particular, <span class="math inline">\(cov(NO3,TN)=68.57\)</span>, <span class="math inline">\(cov(SO4,MG)=19.83\)</span> and <span class="math inline">\(cov(CA,H)=-7.64\)</span>. However, at the scale of covariances we cannot judge the strengths of the associations, because the magnitude of the covariance is determined by the diagonal variance terms of the respective variables. We need to normalise by those variances, i.e. look at the correlation matrix:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="08-multivariate.html#cb162-1" tabindex="-1"></a><span class="fu">cor</span>(streams_log[,<span class="dv">6</span><span class="sc">:</span><span class="dv">15</span>])</span></code></pre></div>
<pre><code>##          NO3       TON       TN      NH4      DOC
## NO3  1.00000 -0.396312  0.98287 -0.19283  0.09091
## TON -0.39631  1.000000 -0.24376  0.15818  0.18462
## TN   0.98287 -0.243763  1.00000 -0.16373  0.11021
## NH4 -0.19283  0.158179 -0.16373  1.00000 -0.38187
## DOC  0.09091  0.184623  0.11021 -0.38187  1.00000
## SO4 -0.04102  0.053697  0.02222  0.09709 -0.34742
## CL  -0.41974  0.132144 -0.41437  0.27956 -0.16068
## CA   0.24239 -0.161289  0.25675  0.05642 -0.26636
## MG  -0.33487  0.400848 -0.23763  0.20783 -0.35195
## H    0.06058 -0.009585  0.03146 -0.20592  0.41182
##          SO4      CL       CA      MG         H
## NO3 -0.04102 -0.4197  0.24239 -0.3349  0.060584
## TON  0.05370  0.1321 -0.16129  0.4008 -0.009585
## TN   0.02222 -0.4144  0.25675 -0.2376  0.031458
## NH4  0.09709  0.2796  0.05642  0.2078 -0.205917
## DOC -0.34742 -0.1607 -0.26636 -0.3519  0.411824
## SO4  1.00000  0.2559  0.48168  0.7414 -0.454846
## CL   0.25589  1.0000  0.16475  0.5523 -0.334131
## CA   0.48168  0.1648  1.00000  0.3781 -0.812295
## MG   0.74138  0.5523  0.37810  1.0000 -0.545448
## H   -0.45485 -0.3341 -0.81230 -0.5454  1.000000</code></pre>
<p>Now the magnitude of the association is easier to see: <span class="math inline">\(corr(NO3,TN)=0.98\)</span>, <span class="math inline">\(corr(SO4,MG)=0.74\)</span> and <span class="math inline">\(corr(CA,H)=-0.81\)</span>.</p>
</div>
<div id="linear-combination-of-variables" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Linear combination of variables<a href="08-multivariate.html#linear-combination-of-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A first step in multivariate analyses (PCA, DFA, FA etc.) is usually to centre the variables to zero mean: <span class="math inline">\(y^*=y-\mu\)</span> so that <span class="math inline">\(\mu^*=0\)</span> and <span class="math inline">\(\sigma^*=\sigma\)</span>. Compare Chapter <a href="02-math.html#math">1</a>.</p>
<p>Then, the fundamental concept underlying multivariate analyses is to derive new linear combinations of the variables that summarise the variation in the original data set:</p>
<p><span class="math display" id="eq:lincomb">\[\begin{equation}
z_{ik}=u_{1k}\cdot y_{i1}+u_{2k}\cdot y_{i2}+\ldots+u_{pk}\cdot y_{ip}
\tag{7.4}
\end{equation}\]</span></p>
<p><span class="math inline">\(z_{ik}\)</span> is the value of the <em>new</em> variable <span class="math inline">\(k\)</span> for object <span class="math inline">\(i\)</span>. The object is a datapoint for a timestep, spatial location or else. <span class="math inline">\(u_{1k},\ldots,u_{pk}\)</span> are the <em>coefficients</em> indicating how much each original variable contributes to the linear combination. This is the so called <em>Eigenvector</em> of the covariance matrix (more on this later). <span class="math inline">\(y_{i1},\ldots,y_{ip}\)</span> are the values of the <em>original</em> variables <span class="math inline">\(1,\ldots,p\)</span> for object <span class="math inline">\(i\)</span>.</p>
<p>The new variables are called (depending on the method) <strong>principal components</strong>, factors or discriminant functions. They are extracted so that the first explains most of the variance in the original variables, the second explains most of the remaining variance after the first has been extracted but is <em>independent</em> of (uncorrelated with) the first … and so on. The number of new variables <span class="math inline">\(k\)</span> is the same as the number of original variables <span class="math inline">\(p\)</span>, although the variance is usually consolidated in the first few new variables. The unknown coefficients <span class="math inline">\(u_{1k},\ldots,u_{pk}\)</span> are determined via so called <strong>Eigenanalysis</strong> (see below).</p>
<p>A graphical explanation of what PCA does is <strong>axis rotation</strong>. We illustrate this with an example in 2D from <span class="citation">Green (<a href="#ref-green1997">1997</a>)</span>, cited in <span class="citation">Quinn and Keough (<a href="#ref-quinn2002">2002</a>)</span>; total biomass of red land crabs against number of burrows at ten forested sites on Christmas Island (Figure <a href="08-multivariate.html#fig:crabs1">7.2</a>). When the data are centred then the origin is where the individual means intersect (the centroid); the original axes are the black lines in the plots. Through PCA, the original axes are now rotated such that the 1st new one (PC1 in red) goes in the direction of the greatest spread of points and the 2nd new axis (PC2 in red), still perpendicular, covers the secondary variation. This is also the principle with more dimensions, though we cannot visualise it anymore.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:crabs1"></span>
<img src="qm4g_files/figure-html/crabs1-1.png" alt="Total biomass of red land crabs against number of burrows at ten forested sites on Christmas Island. When the data are centred then the origin is where the individual means intersect (the centroid); the original axes are the black lines in the plots. Through PCA, the original axes are rotated such that the 1st new one (PC1 in red) goes in the direction of the greatest spread of points and the 2nd new axis (PC2 in red), still perpendicular, covers the secondary variation. For one data point, marked by the cross, the new coordinates in PC1 and PC2 direction are marked in blue and green, respectively. After: @quinn2002, based on data by @green1997." width="672" />
<p class="caption">
Figure 7.2: Total biomass of red land crabs against number of burrows at ten forested sites on Christmas Island. When the data are centred then the origin is where the individual means intersect (the centroid); the original axes are the black lines in the plots. Through PCA, the original axes are rotated such that the 1st new one (PC1 in red) goes in the direction of the greatest spread of points and the 2nd new axis (PC2 in red), still perpendicular, covers the secondary variation. For one data point, marked by the cross, the new coordinates in PC1 and PC2 direction are marked in blue and green, respectively. After: <span class="citation">Quinn and Keough (<a href="#ref-quinn2002">2002</a>)</span>, based on data by <span class="citation">Green (<a href="#ref-green1997">1997</a>)</span>.
</p>
</div>
<p>Let us look at one data point, marked by the cross in Figure <a href="08-multivariate.html#fig:crabs1">7.2</a>. The new coordinate in PC1 direction, marked in blue in the plot, is calculated after Equation <a href="08-multivariate.html#eq:lincomb">(7.4)</a> as:
<span class="math display" id="eq:zi1">\[\begin{equation}
\color{blue}{z_{i1}=u_{11}\cdot y_{i1}+u_{21}\cdot y_{i2}}
\tag{7.5}
\end{equation}\]</span></p>
<p>The new coordinate in PC2 direction, marked in green in the plot, is calculated after Equation <a href="08-multivariate.html#eq:lincomb">(7.4)</a> as:
<span class="math display" id="eq:zi2">\[\begin{equation}
\color{green}{z_{i2}=u_{12}\cdot y_{i1}+u_{22}\cdot y_{i2}}
\tag{7.6}
\end{equation}\]</span></p>
<p>To see how this is a rotation consider Figure <a href="08-multivariate.html#fig:rotation">7.3</a>: After rotating the <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> axes by angle <span class="math inline">\(\alpha\)</span>, the new coordinates <span class="math inline">\(x&#39;\)</span> and <span class="math inline">\(y&#39;\)</span> of point <span class="math inline">\(P\)</span> are:
<span class="math display" id="eq:xtick">\[\begin{equation}
x&#39;=\cos\alpha\cdot x+\sin\alpha\cdot y
\tag{7.7}
\end{equation}\]</span>
<span class="math display" id="eq:ytick">\[\begin{equation}
y&#39;=-\sin\alpha\cdot x+\cos\alpha\cdot y
\tag{7.8}
\end{equation}\]</span></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rotation"></span>
<img src="figs/Coordinate_system_rotation_svg.svg" alt="Geometric derivation of the new coordinates of a point $P$ after rotating the $x$ and $y$ axes by an angle $\alpha$. Note that $\sin\alpha=\frac{opposite}{hypotenuse}$ and $\cos\alpha=\frac{adjacent}{hypotenuse}$. &lt;br&gt;&lt;small&gt;By Jochen Burghardt - Own work, CC BY-SA 4.0, https://commons.wikimedia.org/w/index.php?curid=71157895.&lt;/small&gt;" width="80%" />
<p class="caption">
Figure 7.3: Geometric derivation of the new coordinates of a point <span class="math inline">\(P\)</span> after rotating the <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> axes by an angle <span class="math inline">\(\alpha\)</span>. Note that <span class="math inline">\(\sin\alpha=\frac{opposite}{hypotenuse}\)</span> and <span class="math inline">\(\cos\alpha=\frac{adjacent}{hypotenuse}\)</span>. <br><small>By Jochen Burghardt - Own work, CC BY-SA 4.0, <a href="https://commons.wikimedia.org/w/index.php?curid=71157895" class="uri">https://commons.wikimedia.org/w/index.php?curid=71157895</a>.</small>
</p>
</div>
<p>Equations <a href="08-multivariate.html#eq:zi1">(7.5)</a> and <a href="08-multivariate.html#eq:xtick">(7.7)</a>, and <a href="08-multivariate.html#eq:zi2">(7.6)</a> and <a href="08-multivariate.html#eq:ytick">(7.8)</a> are equivalent.</p>
</div>
<div id="eigenanalysis" class="section level3 hasAnchor" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Eigenanalysis<a href="08-multivariate.html#eigenanalysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The vector of coefficients <span class="math inline">\(\begin{pmatrix}u_{1k}&amp;\ldots&amp;u_{pk}\end{pmatrix}^T\)</span> in Equation <a href="08-multivariate.html#eq:lincomb">(7.4)</a> is called the <span class="math inline">\(k\)</span>th <strong>Eigenvector</strong>. The Eigenvectors span the new coordinate system after rotation as illustrated in Figure <a href="08-multivariate.html#fig:crabs2">7.4</a>: The first Eigenvector is <span class="math inline">\(\color{blue}{\begin{pmatrix}u_{11}&amp;u_{21}\end{pmatrix}^T}\)</span> and the second Eigenvector is <span class="math inline">\(\color{green}{\begin{pmatrix}u_{12}&amp;u_{22}\end{pmatrix}^T}\)</span>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:crabs2"></span>
<img src="qm4g_files/figure-html/crabs2-1.png" alt="PCA of the crabs dataset as axis rotation. The two **Eigenvectors** spanning the new coordinate system are marked in blue and green. After: @quinn2002, based on data by @green1997." width="672" />
<p class="caption">
Figure 7.4: PCA of the crabs dataset as axis rotation. The two <strong>Eigenvectors</strong> spanning the new coordinate system are marked in blue and green. After: <span class="citation">Quinn and Keough (<a href="#ref-quinn2002">2002</a>)</span>, based on data by <span class="citation">Green (<a href="#ref-green1997">1997</a>)</span>.
</p>
</div>
<p>The Eigenvectors are found so that the following equation holds:<a href="#fn28" class="footnote-ref" id="fnref28"><sup>28</sup></a></p>
<p><span class="math display" id="eq:eigen">\[\begin{equation}
\mathbf{C}\cdot\begin{pmatrix}
u_{1k}\\u_{2k}\\\vdots\\u_{pk}
\end{pmatrix}=\lambda_k\cdot\begin{pmatrix}
u_{1k}\\u_{2k}\\\vdots\\u_{pk}
\end{pmatrix}
\tag{7.9}
\end{equation}\]</span></p>
<p><span class="math inline">\(\mathbf{C}\)</span> is the covariance matrix and <span class="math inline">\(\lambda_1,\ldots,\lambda_k\)</span> are the so called <strong>Eigenvalues</strong>, which equal the amount of variance explained by each new variable. The sum of variances (Eigenvalues) of the new variables equals the sum of variances of the original variables.</p>
<p>Determining the Eigenvectors and Eigenvalues is called Eigenanalysis. The Eigenanalysis can be carried out on the covariance matrix <span class="math inline">\(\mathbf{C}\)</span> or the correlation matrix <span class="math inline">\(\mathbf{R}\)</span> using <em>Spectral Decomposition (Eigendecomposition)</em> or on the data matrix (raw, centred or standardised) using <em>Singular Value Decomposition</em>, which is the more general method. We do not go into the details of these techniques here.</p>
<p>If the Eigenanalysis is carried out on the covariance matrix <span class="math inline">\(\mathbf{C}\)</span> then <span class="math inline">\(\sum_{j=1}^{k}\lambda_j=Tr(\mathbf{C})\)</span>, i.e. the sum of the Eigenvalues is the trace of <span class="math inline">\(\mathbf{C}\)</span>. The <strong>trace</strong> is defined as the sum of the diagonal elements of a matrix, i.e. here the sum of the variances of the original <em>centred</em> variables. This is appropriate when the variables are measured in comparable units and differences in variance make an important contribution to interpretation.</p>
<p>If the Eigenanalysis is carried out on the correlation matrix <span class="math inline">\(\mathbf{R}\)</span> then <span class="math inline">\(\sum_{j=1}^{k}\lambda_j=Tr(\mathbf{R})\)</span>, i.e. the sum of the variances of the original <em>standardised</em> variables: <span class="math inline">\(y^*=\frac{y-\mu}{\sigma}\)</span> so that <span class="math inline">\(\mu^*=0\)</span> and <span class="math inline">\(\sigma^*=1\)</span>. Compare Chapter <a href="02-math.html#math">1</a>. This is necessary when variables are measured in very different units or scales, otherwise variables with large values/variances may dominate the results.</p>
<p>In the stream chemistry example we best work with standardised data because variances are orders of magnitude different.<a href="#fn29" class="footnote-ref" id="fnref29"><sup>29</sup></a> We use the <code>prcomp()</code> function on the data matrix, and tell it to standardise the variables by <code>scale=TRUE</code>. To only centre the variables we would use <code>center=TRUE</code> and <code>scale=FALSE</code> (which is the default).</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="08-multivariate.html#cb164-1" tabindex="-1"></a>streams_pca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(streams_log[,<span class="dv">6</span><span class="sc">:</span><span class="dv">15</span>], <span class="at">scale=</span><span class="cn">TRUE</span>)</span>
<span id="cb164-2"><a href="08-multivariate.html#cb164-2" tabindex="-1"></a>streams_pca</span></code></pre></div>
<pre><code>## Standard deviations (1, .., p=10):
##  [1] 1.85038 1.57255 1.08217 0.96516 0.86381 0.80397
##  [7] 0.61930 0.36161 0.30237 0.04784
## 
## Rotation (n x k) = (10 x 10):
##         PC1      PC2       PC3      PC4      PC5
## NO3 -0.2608  0.51883  0.048949  0.22992 -0.02958
## TON  0.1471 -0.29927  0.515134  0.54376 -0.11856
## TN  -0.2285  0.51019  0.153554  0.34323 -0.02311
## NH4  0.2280 -0.07531 -0.486776  0.65372 -0.26640
## DOC -0.2883 -0.14662  0.562051 -0.09029 -0.43309
## SO4  0.3685  0.22498  0.241733  0.01627  0.53820
## CL   0.3579 -0.15796 -0.017738 -0.16533 -0.32511
## CA   0.2811  0.44581  0.080590 -0.18762 -0.36044
## MG   0.4716  0.01539  0.300889  0.10731  0.23554
## H   -0.3972 -0.28149  0.005572  0.15439  0.38113
##         PC6     PC7      PC8      PC9      PC10
## NO3 -0.2391 -0.1623  0.05637 -0.03010 -0.720449
## TON  0.3030 -0.2980 -0.28358 -0.20553 -0.102368
## TN  -0.1994 -0.1805  0.05424 -0.04787  0.684124
## NH4 -0.1033  0.4320  0.06398  0.07470 -0.011424
## DOC -0.2022  0.5398  0.22175  0.04693 -0.013216
## SO4 -0.1550  0.4838 -0.15731 -0.42645 -0.023891
## CL  -0.7380 -0.2988 -0.19878 -0.19926  0.021153
## CA   0.2313  0.1588 -0.57822  0.37080  0.006384
## MG  -0.1421 -0.1313  0.41741  0.63807 -0.031886
## H   -0.3425  0.0924 -0.53606  0.42495  0.008250</code></pre>
<p>In the output, what is called “standard deviations” are the square roots of the Eigenvalues of the principal components (PCs). So squaring them yields the Eigenvalues:</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="08-multivariate.html#cb166-1" tabindex="-1"></a>ev <span class="ot">&lt;-</span> streams_pca<span class="sc">$</span>sdev<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb166-2"><a href="08-multivariate.html#cb166-2" tabindex="-1"></a>ev</span></code></pre></div>
<pre><code>##  [1] 3.423924 2.472900 1.171093 0.931534 0.746173
##  [6] 0.646363 0.383537 0.130760 0.091428 0.002288</code></pre>
<p>We can verify that in this example the Eigenvalues sum to 10, which is the trace of the correlation matrix:</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="08-multivariate.html#cb168-1" tabindex="-1"></a><span class="fu">sum</span>(ev)</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>By normalising the Eigenvalues by 10 we get the fraction of original variance explained by each PC:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="08-multivariate.html#cb170-1" tabindex="-1"></a>ev<span class="sc">/</span><span class="fu">sum</span>(ev)<span class="sc">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>##  [1] 34.23924 24.72900 11.71093  9.31534  7.46173
##  [6]  6.46363  3.83537  1.30760  0.91428  0.02288</code></pre>
<p>Plotting the Eigenvalues in a <strong>screeplot</strong> shows that the bulk of the original variance is consolidated in the first three PCs; together they explain 71% of the original variance:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="08-multivariate.html#cb172-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">10</span>,<span class="dv">1</span>), ev, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">type =</span> <span class="st">&#39;b&#39;</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">4</span>),</span>
<span id="cb172-2"><a href="08-multivariate.html#cb172-2" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Principal Component&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Eigenvalue&quot;</span>)</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-54-1.png" width="80%" /></p>
<p>What’s called “rotation” in the output are the Eigenvectors, measuring how much much each original variable contributes to the PCs. We look at the Eigenvectors of the first three PCs only here:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="08-multivariate.html#cb173-1" tabindex="-1"></a>streams_pca<span class="sc">$</span>rotation[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span></code></pre></div>
<pre><code>##         PC1      PC2       PC3
## NO3 -0.2608  0.51883  0.048949
## TON  0.1471 -0.29927  0.515134
## TN  -0.2285  0.51019  0.153554
## NH4  0.2280 -0.07531 -0.486776
## DOC -0.2883 -0.14662  0.562051
## SO4  0.3685  0.22498  0.241733
## CL   0.3579 -0.15796 -0.017738
## CA   0.2811  0.44581  0.080590
## MG   0.4716  0.01539  0.300889
## H   -0.3972 -0.28149  0.005572</code></pre>
<p>We see that SO4, log(Cl) and Mg load strongly positively on PC1 and log(H) loads strongly negatively. It seems PC1 distinguishes alkaline from acidic sites. NO3, total nitrogen and Ca load strongly positively on PC2. The correlation between total nitrogen and NO3 is again apparent. My interpretation is that PC2 distinguishes subsurface (high Ca, high nitrogen) from surface water sites. Total organic nitrogen and log(dissolved organic carbon) load strongly positively on PC3 and NH4 loads strongly negatively. PC3 might distinguish organic from mineralised (surface) water sites. We can also visualise this in so called <strong>biplots</strong>:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="08-multivariate.html#cb175-1" tabindex="-1"></a><span class="fu">biplot</span>(streams_pca, <span class="at">choices=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb175-2"><a href="08-multivariate.html#cb175-2" tabindex="-1"></a><span class="fu">biplot</span>(streams_pca, <span class="at">choices=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb175-3"><a href="08-multivariate.html#cb175-3" tabindex="-1"></a><span class="fu">biplot</span>(streams_pca, <span class="at">choices=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-56-1.png" width="33%" /><img src="qm4g_files/figure-html/unnamed-chunk-56-2.png" width="33%" /><img src="qm4g_files/figure-html/unnamed-chunk-56-3.png" width="33%" /></p>
<p>In these plots we see the original data points (black numbers) in PC space. The red vectors show the contributions of the original variables to the PCs. Vectors close together in all three dimensions indicate correlation; we can see this best here for NO3 and total nitrogen.</p>
<p>Lastly, in order to shows what we can do with the PCs, we extract the values of the first three PCs and plot them against the other catchment characteristics in the dataset:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="08-multivariate.html#cb176-1" tabindex="-1"></a><span class="fu">library</span>(latex2exp)</span>
<span id="cb176-2"><a href="08-multivariate.html#cb176-2" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>){</span>
<span id="cb176-3"><a href="08-multivariate.html#cb176-3" tabindex="-1"></a>  <span class="fu">plot</span>(streams_pca<span class="sc">$</span>x[,i],streams_log<span class="sc">$</span>max_elev, <span class="at">xlab=</span><span class="fu">paste</span>(<span class="st">&quot;PC&quot;</span>,i), <span class="at">ylab=</span><span class="st">&quot;Max. elevation&quot;</span>,</span>
<span id="cb176-4"><a href="08-multivariate.html#cb176-4" tabindex="-1"></a>       <span class="at">main=</span><span class="fu">TeX</span>(<span class="fu">paste</span>(<span class="st">&quot;$</span><span class="sc">\\</span><span class="st">rho$=&quot;</span>,<span class="fu">round</span>(<span class="fu">cor</span>(streams_pca<span class="sc">$</span>x[,i],streams_log<span class="sc">$</span>sample_elev),<span class="at">digits=</span><span class="dv">3</span>))))</span>
<span id="cb176-5"><a href="08-multivariate.html#cb176-5" tabindex="-1"></a>  <span class="fu">plot</span>(streams_pca<span class="sc">$</span>x[,i],streams_log<span class="sc">$</span>sample_elev, <span class="at">xlab=</span><span class="fu">paste</span>(<span class="st">&quot;PC&quot;</span>,i), <span class="at">ylab=</span><span class="st">&quot;Sample elevation&quot;</span>,</span>
<span id="cb176-6"><a href="08-multivariate.html#cb176-6" tabindex="-1"></a>       <span class="at">main=</span><span class="fu">TeX</span>(<span class="fu">paste</span>(<span class="st">&quot;$</span><span class="sc">\\</span><span class="st">rho$=&quot;</span>,<span class="fu">round</span>(<span class="fu">cor</span>(streams_pca<span class="sc">$</span>x[,i],streams_log<span class="sc">$</span>stream_length),<span class="at">digits=</span><span class="dv">3</span>))))</span>
<span id="cb176-7"><a href="08-multivariate.html#cb176-7" tabindex="-1"></a>  <span class="fu">plot</span>(streams_pca<span class="sc">$</span>x[,i],streams_log<span class="sc">$</span>stream_length, <span class="at">xlab=</span><span class="fu">paste</span>(<span class="st">&quot;PC&quot;</span>,i), <span class="at">ylab=</span><span class="st">&quot;Stream length&quot;</span>,</span>
<span id="cb176-8"><a href="08-multivariate.html#cb176-8" tabindex="-1"></a>       <span class="at">main=</span><span class="fu">TeX</span>(<span class="fu">paste</span>(<span class="st">&quot;$</span><span class="sc">\\</span><span class="st">rho$=&quot;</span>,<span class="fu">round</span>(<span class="fu">cor</span>(streams_pca<span class="sc">$</span>x[,i],streams_log<span class="sc">$</span>catchm_area),<span class="at">digits=</span><span class="dv">3</span>))))</span>
<span id="cb176-9"><a href="08-multivariate.html#cb176-9" tabindex="-1"></a>  <span class="fu">plot</span>(streams_pca<span class="sc">$</span>x[,i],streams_log<span class="sc">$</span>catchm_area, <span class="at">xlab=</span><span class="fu">paste</span>(<span class="st">&quot;PC&quot;</span>,i), <span class="at">ylab=</span><span class="st">&quot;Catchment area&quot;</span>,</span>
<span id="cb176-10"><a href="08-multivariate.html#cb176-10" tabindex="-1"></a>       <span class="at">main=</span><span class="fu">TeX</span>(<span class="fu">paste</span>(<span class="st">&quot;$</span><span class="sc">\\</span><span class="st">rho$=&quot;</span>,<span class="fu">round</span>(<span class="fu">cor</span>(streams_pca<span class="sc">$</span>x[,i],streams_log<span class="sc">$</span>max_elev),<span class="at">digits=</span><span class="dv">3</span>))))</span>
<span id="cb176-11"><a href="08-multivariate.html#cb176-11" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-57-1.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-2.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-3.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-4.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-5.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-6.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-7.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-8.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-9.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-10.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-11.png" width="25%" /><img src="qm4g_files/figure-html/unnamed-chunk-57-12.png" width="25%" /></p>
<p>On top of these plots are the linear correlation coefficients <span class="math inline">\(\rho\)</span> as a first indication of associations between PCs and other catchment characteristics. The strongest correlation is that between PC1 and maximum elevation. Given our interpretation of PC1 from above we can conclude that waters tend to get more acidic (less alkaline) with elevation, perhaps because these sites are less influenced by human activity that tends to introduce alkalinity through agricultural or urban runoff and discharges.</p>
<p>We could also use the PCs as predictors in a regression model. This is especially useful for predictors that are highly correlated; these we can consolidate in a few PCs that then serve as independent predictors. Interpretation, however - as the stream chemistry example demonstrates - may be challenging.</p>
</div>
</div>
<div id="manova" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Multivariate ANOVA (MANOVA)<a href="08-multivariate.html#manova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>MANOVA extends ANOVA to the case of multiple response variables. Let us remind ourselves (compare Chapter <a href="04-categorical_vars.html#categoricalvars">3</a>) that the categorical predictor variables are called <strong>factors</strong>, the categories of each factor are called <strong>levels</strong>, <strong>groups</strong> or <strong>treatments</strong>. And the parameters are called <strong>effects</strong>. Where ANOVA asks whether <em>means</em> across factor levels (groups) are significantly different (compare the yields example from Chapter <a href="04-categorical_vars.html#categoricalvars">3</a>), MANOVA asks whether <em>centroids</em> across factor levels (groups) are significantly different, taking all response variables together.</p>
<p>We illustrate <strong>single-factor MANOVA</strong> with a marine sediment dataset from <span class="citation">Haynes et al. (<a href="#ref-haynes1995">1995</a>)</span>, cited in <span class="citation">Quinn and Keough (<a href="#ref-quinn2002">2002</a>)</span>. We use this dataset to test for differences between sites in trace metal concentrations in marine sediments off the Victorian coast in southern Australia:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="08-multivariate.html#cb177-1" tabindex="-1"></a><span class="co"># load sediments data</span></span>
<span id="cb177-2"><a href="08-multivariate.html#cb177-2" tabindex="-1"></a>sediments <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/sediments.txt&quot;</span>,<span class="at">header=</span>T)</span>
<span id="cb177-3"><a href="08-multivariate.html#cb177-3" tabindex="-1"></a>sediments</span></code></pre></div>
<pre><code>##        site    CU    PB    NI    MN
## 1    Delray  7.15 12.00  7.40 137.0
## 2    Delray  5.85  6.35  7.05 106.5
## 3    Delray  5.45  4.95 10.40 102.5
## 4    Delray  8.50  7.05  6.40 125.0
## 5  Seaspray  9.45 10.50 12.15 162.5
## 6  Seaspray  6.30 18.35 11.85 129.5
## 7  Seaspray  7.80 18.10 10.70 224.5
## 8  Seaspray  9.15 16.55 12.20 247.0
## 9  Woodside 10.80 28.90 18.30 403.5
## 10 Woodside 21.20 11.60 18.20 377.0
## 11 Woodside 18.20 13.85 15.30 256.0
## 12 Woodside  7.60  9.35  9.25 440.0</code></pre>
<p>“Delray Beach” is a site of a proposed wastewater outfall, and “Seaspray” and “Woodside” are two possible control sites. At each site, two sediment cores were taken at four randomly chosen locations and analysed for trace metals (CU=copper, PB=lead, NI=nickel, MN=manganese). The results from the two cores were averaged. So we have <span class="math inline">\(n=12\)</span> objects here, the rows, and <span class="math inline">\(p=4\)</span> response variables, the columns. MANOVA tests for the effects of site on the response variables <em>taken together</em>. A first thing to do - as always - is to look at the scatterplot matrix, with datapoints coloured by site:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="08-multivariate.html#cb179-1" tabindex="-1"></a><span class="fu">pairs</span>(sediments[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], <span class="at">diag.panel =</span> panel.hist, <span class="at">lower.panel =</span> panel.cor,</span>
<span id="cb179-2"><a href="08-multivariate.html#cb179-2" tabindex="-1"></a>      <span class="at">pch=</span><span class="dv">21</span>, <span class="at">bg=</span><span class="fu">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>)[<span class="fu">as.factor</span>(sediments<span class="sc">$</span>site)])</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-60-1.png" width="80%" /></p>
<p>We notice strong correlations between variables. And log-transformation of all variables looks like a good idea to make the residuals later on adhere better to the normality assumption:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="08-multivariate.html#cb180-1" tabindex="-1"></a>sediments_log <span class="ot">&lt;-</span> sediments</span>
<span id="cb180-2"><a href="08-multivariate.html#cb180-2" tabindex="-1"></a>sediments_log[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">log</span>(sediments[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb180-3"><a href="08-multivariate.html#cb180-3" tabindex="-1"></a><span class="fu">pairs</span>(sediments_log[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], <span class="at">diag.panel =</span> panel.hist, <span class="at">lower.panel =</span> panel.cor,</span>
<span id="cb180-4"><a href="08-multivariate.html#cb180-4" tabindex="-1"></a>      <span class="at">pch=</span><span class="dv">21</span>, <span class="at">bg=</span><span class="fu">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>)[<span class="fu">as.factor</span>(sediments_log<span class="sc">$</span>site)])</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-61-1.png" width="80%" /></p>
<p>The best single discriminator of the groups seems to be manganese; this will be confirmed by DFA in Chapter <a href="08-multivariate.html#dfa">7.4</a>. The covariance and correlation matrices look as follows:</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="08-multivariate.html#cb181-1" tabindex="-1"></a><span class="fu">cov</span>(sediments_log[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div>
<pre><code>##         CU      PB     NI     MN
## CU 0.17591 0.07361 0.1011 0.1421
## PB 0.07361 0.25382 0.1074 0.1485
## NI 0.10106 0.10741 0.1209 0.1190
## MN 0.14214 0.14848 0.1190 0.2795</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="08-multivariate.html#cb183-1" tabindex="-1"></a><span class="fu">cor</span>(sediments_log[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div>
<pre><code>##        CU     PB     NI     MN
## CU 1.0000 0.3483 0.6930 0.6411
## PB 0.3483 1.0000 0.6131 0.5575
## NI 0.6930 0.6131 1.0000 0.6475
## MN 0.6411 0.5575 0.6475 1.0000</code></pre>
<p>Like PCA, MANOVA begins by centring the variables and deriving new linear combinations through Equation <a href="08-multivariate.html#eq:lincomb">(7.4)</a>. For the sediments data, the equation is:
<span class="math display" id="eq:lincombsed">\[\begin{equation}
z_{ik}=u_{1k}\cdot(\log Cu)_i+u_{2k}\cdot(\log Pb)_i+u_{3k}\cdot(\log Ni)_i+u_{4k}\cdot(\log Mn)_i
\tag{7.10}
\end{equation}\]</span></p>
<p>MANOVA then finds the linear combination <span class="math inline">\(z_k\)</span> of response variables which <em>maximises the between-group variance:within-group variance ratio</em> of the data. This is called the <strong>1st discriminant function</strong>; similar, but not identical, to the 1st principal component in PCA.<a href="#fn30" class="footnote-ref" id="fnref30"><sup>30</sup></a> The Null hypothesis of MANOVA is that there are no differences between factor level centroids. Before testing this hypothesis, MANOVA proceeds through the following steps.</p>
<div id="steps-of-manova" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Steps of MANOVA<a href="08-multivariate.html#steps-of-manova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The first step is to calculate sums-of-squares-and-cross-products (SSCP) matrices:</p>
<ol style="list-style-type: decimal">
<li>The <strong>total matrix</strong> <span class="math inline">\(\mathbf T\)</span>, replacing SSY of ANOVA (compare Figure <a href="04-categorical_vars.html#fig:anovassysse">3.2</a>, left)<a href="#fn31" class="footnote-ref" id="fnref31"><sup>31</sup></a></li>
</ol>
<p><span class="math display" id="eq:totalmatrix">\[\begin{equation}
\mathbf T=\begin{pmatrix}
\sum_{i=1}^{n}\left(y_{i1}-\bar y_1\right)^2 &amp; \cdots &amp; \sum_{i=1}^{n}\left(y_{ip}-\bar y_p\right)\cdot\left(y_{i1}-\bar y_1\right) \\
\vdots &amp; \ddots &amp; \vdots \\
\sum_{i=1}^{n}\left(y_{i1}-\bar y_1\right)\cdot\left(y_{ip}-\bar y_p\right) &amp; \cdots &amp; \sum_{i=1}^{n}\left(y_{ip}-\bar y_p\right)^2
\end{pmatrix}
\tag{7.11}
\end{equation}\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>The <strong>error (or residual) matrix</strong> <span class="math inline">\(\mathbf E\)</span> (“within-group SSCP”), replacing SSE of ANOVA (compare Figure <a href="04-categorical_vars.html#fig:anovassysse">3.2</a>, right)<a href="#fn32" class="footnote-ref" id="fnref32"><sup>32</sup></a></li>
</ol>
<p><span class="math display" id="eq:errormatrix">\[\begin{equation}
\mathbf E=\begin{pmatrix}
\sum_{j=1}^{k}\sum_{i=1}^{n_j}\left(y_{ji1}-\bar y_{j1}\right)^2 &amp; \cdots &amp; \sum_{j=1}^{k}\sum_{i=1}^{n_j}\left(y_{jip}-\bar y_{jp}\right)\cdot\left(y_{ji1}-\bar y_{j1}\right) \\
\vdots &amp; \ddots &amp; \vdots \\
\sum_{j=1}^{k}\sum_{i=1}^{n_j}\left(y_{ji1}-\bar y_{j1}\right)\cdot\left(y_{jip}-\bar y_{jp}\right) &amp; \cdots &amp; \sum_{j=1}^{k}\sum_{i=1}^{n_j}\left(y_{jip}-\bar y_{jp}\right)^2
\end{pmatrix}
\tag{7.12}
\end{equation}\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>The <strong>hypothesis (or effect) matrix</strong> <span class="math inline">\(\mathbf H=\mathbf T-\mathbf E\)</span> (“between-group SSCP”), replacing SSA of ANOVA</li>
</ol>
<p>The second step is to calculate the <strong>between-group SSCP:within-group SSCP ratio</strong>:
<span class="math display" id="eq:heinv">\[\begin{equation}
\mathbf H\cdot\mathbf E^{-1}
\tag{7.13}
\end{equation}\]</span></p>
<p>This replaces the F statistic <span class="math inline">\(\frac{\frac{SSA}{k-1}}{\frac{SSE}{n-k}}\)</span> of ANOVA.</p>
<p>The third step is to perform an Eigenanalysis of the resulting matrix <span class="math inline">\(\mathbf H\cdot\mathbf E^{-1}\)</span>, like in PCA.<a href="#fn33" class="footnote-ref" id="fnref33"><sup>33</sup></a> The resulting Eigenvectors contain the coefficients <span class="math inline">\(u\)</span> of Equation <a href="08-multivariate.html#eq:lincombsed">(7.10)</a>. Their Eigenvalues measure how much of the between-group SSCP:within-group SSCP ratio is explained by each Eigenvector. As with PCA, the sum of the Eigenvalues is the trace of the matrix <span class="math inline">\(\mathbf H\cdot\mathbf E^{-1}\)</span>: <span class="math inline">\(Tr\left(\mathbf H\cdot\mathbf E^{-1}\right)=\sum_{i=1}^{p}diag\left(\mathbf H\cdot\mathbf E^{-1}\right)\)</span>, i.e. the sum of the univariate between-group SSCP:within-group SSCP ratios.</p>
<p>Fourth, the linear combination producing the largest eigenvalue maximises the between-group variance:within-group variance ratio, with the Eigenvector containing the coefficients <span class="math inline">\(u\)</span>.</p>
<p>Let us perform the MANOVA for the marine sediments example:</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="08-multivariate.html#cb185-1" tabindex="-1"></a><span class="co"># perform MANOVA</span></span>
<span id="cb185-2"><a href="08-multivariate.html#cb185-2" tabindex="-1"></a>sediments_fit <span class="ot">&lt;-</span> <span class="fu">manova</span>(<span class="fu">cbind</span>(CU,PB,NI,MN) <span class="sc">~</span> site, <span class="at">data=</span>sediments_log)</span></code></pre></div>
<p>The SSCP matrices are:</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="08-multivariate.html#cb186-1" tabindex="-1"></a><span class="co"># extract SSCP matrices</span></span>
<span id="cb186-2"><a href="08-multivariate.html#cb186-2" tabindex="-1"></a><span class="fu">summary</span>(sediments_fit)<span class="sc">$</span>SS</span></code></pre></div>
<pre><code>## $site
##        CU     PB     NI    MN
## CU 1.0381 0.8039 0.8717 1.621
## PB 0.8039 1.4460 1.0183 1.457
## NI 0.8717 1.0183 0.8750 1.446
## MN 1.6215 1.4574 1.4456 2.582
## 
## $Residuals
##           CU       PB      NI       MN
## CU  0.896917 0.005757  0.2400 -0.05792
## PB  0.005757 1.346064  0.1632  0.17591
## NI  0.240000 0.163232  0.4549 -0.13642
## MN -0.057919 0.175914 -0.1364  0.49218</code></pre>
<p>“Site” is the effect matrix in our case and “Residuals” is the residual matrix. Hence <span class="math inline">\(\mathbf H\cdot\mathbf E^{-1}\)</span> is:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="08-multivariate.html#cb188-1" tabindex="-1"></a><span class="co"># calculate H E^-1</span></span>
<span id="cb188-2"><a href="08-multivariate.html#cb188-2" tabindex="-1"></a>H <span class="ot">&lt;-</span> <span class="fu">summary</span>(sediments_fit)<span class="sc">$</span>SS<span class="sc">$</span>site</span>
<span id="cb188-3"><a href="08-multivariate.html#cb188-3" tabindex="-1"></a>E <span class="ot">&lt;-</span> <span class="fu">summary</span>(sediments_fit)<span class="sc">$</span>SS<span class="sc">$</span>Residuals</span>
<span id="cb188-4"><a href="08-multivariate.html#cb188-4" tabindex="-1"></a>H_E <span class="ot">&lt;-</span> H <span class="sc">%*%</span> <span class="fu">solve</span>(E)</span></code></pre></div>
<p>The Eigenvalues of <span class="math inline">\(\mathbf H\cdot\mathbf E^{-1}\)</span> are:</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="08-multivariate.html#cb189-1" tabindex="-1"></a><span class="co"># extract Eigenvalues</span></span>
<span id="cb189-2"><a href="08-multivariate.html#cb189-2" tabindex="-1"></a><span class="fu">summary</span>(sediments_fit)<span class="sc">$</span>Eigenvalues</span></code></pre></div>
<pre><code>##       [,1]   [,2]       [,3]       [,4]
## site 9.979 0.5703 -3.809e-16 -3.809e-16</code></pre>
<p>We see that the 1st discriminant function has the largest Eigenvalue and thus maximises the between group variance:within group variance ratio.</p>
</div>
<div id="null-hypothesis-test-of-manova" class="section level3 hasAnchor" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> Null hypothesis test of MANOVA<a href="08-multivariate.html#null-hypothesis-test-of-manova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The null hypothesis that there are no differences between factor level centroids can be tested using a function of the largest Eigenvalue of <span class="math inline">\(\mathbf H\cdot\mathbf E^{-1}\)</span>, i.e. the Eigenvalue of the 1st discriminant function, as the test statistic. This is also called <strong>Roy’s largest root</strong>. The sampling distribution of this statistic is not well understood, however, so it is usually treated as an <em>approximate</em> F statistic, following an F-distribution (analogous to ANOVA). Other choices of the test statistic are possible.</p>
<p>Among these is a function of <strong>Wilk’s lambda</strong>:
<span class="math display" id="eq:wilkslambda">\[\begin{equation}
\frac{|\mathbf E|}{|\mathbf T|}
\tag{7.14}
\end{equation}\]</span></p>
<p>Wilk’s lambda is a measure of how much variance remains <em>unexplained</em> by the model, with smaller values indicating greater group differences. <span class="math inline">\(|M|\)</span> is the so called <strong>determinant</strong> of a matrix <span class="math inline">\(M\)</span>, the generalised variance of that matrix, e.g.:
<span class="math display" id="eq:determinant">\[\begin{equation}
\begin{vmatrix}
a &amp; b &amp; c \\
d &amp; e &amp; f \\
g &amp; h &amp; i \\
\end{vmatrix}=(a\cdot e\cdot i+b\cdot f\cdot g+c\cdot d\cdot h)-(c\cdot e\cdot g+b\cdot d\cdot i+a\cdot f\cdot h)
\tag{7.15}
\end{equation}\]</span></p>
<p>The determinant fulfills the same role as the trace, it just uses more information from the matrix.</p>
<p>Another choice is a function of the <strong>Pillai trace</strong>:
<span class="math display" id="eq:pillaitrace">\[\begin{equation}
Tr\left(\mathbf H\cdot\mathbf T^{-1}\right)
\tag{7.16}
\end{equation}\]</span></p>
<p>This measures of how much variance is <em>explained</em> by the model, with greater values indicating greater group differences.</p>
<p>A fourth choice is a function of the <strong>Hotelling-Lawley trace</strong>:
<span class="math display" id="eq:hltrace">\[\begin{equation}
\frac{|\mathbf H|}{|\mathbf E|}=Tr\left(\mathbf H\cdot\mathbf E^{-1}\right)
\tag{7.17}
\end{equation}\]</span></p>
<p>This measures the ratio of <em>explained to unexplained</em> variance, with greater values indicating greater group differences.</p>
<p>Since the sampling distributions of these statistics are not well understood either, they are again treated as <em>approximate</em> F statistics, following an F-distribution. In practice it is advised to look at all of these variants of the test statistic to see if the results are consistent.</p>
<p>In the marine sediments example, the four test statistics give comparable results, though the test statistic based on the Pillai trace would not meet the conventional significance level of 0.01:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="08-multivariate.html#cb191-1" tabindex="-1"></a><span class="fu">summary</span>(sediments_fit, <span class="at">test =</span><span class="st">&quot;Roy&quot;</span>)</span></code></pre></div>
<pre><code>##           Df  Roy approx F num Df den Df  Pr(&gt;F)    
## site       2 9.98     17.5      4      7 0.00095 ***
## Residuals  9                                        
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="08-multivariate.html#cb193-1" tabindex="-1"></a><span class="fu">summary</span>(sediments_fit, <span class="at">test =</span><span class="st">&quot;Wilks&quot;</span>)</span></code></pre></div>
<pre><code>##           Df Wilks approx F num Df den Df Pr(&gt;F)   
## site       2 0.058     4.73      8     12 0.0082 **
## Residuals  9                                       
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="08-multivariate.html#cb195-1" tabindex="-1"></a><span class="fu">summary</span>(sediments_fit, <span class="at">test =</span><span class="st">&quot;Pillai&quot;</span>)</span></code></pre></div>
<pre><code>##           Df Pillai approx F num Df den Df Pr(&gt;F)  
## site       2   1.27     3.06      8     14  0.032 *
## Residuals  9                                       
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="08-multivariate.html#cb197-1" tabindex="-1"></a><span class="fu">summary</span>(sediments_fit, <span class="at">test =</span><span class="st">&quot;Hotelling-Lawley&quot;</span>)</span></code></pre></div>
<pre><code>##           Df Hotelling-Lawley approx F num Df den Df
## site       2             10.6     6.59      8     10
## Residuals  9                                        
##           Pr(&gt;F)   
## site      0.0038 **
## Residuals          
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We may still conclude that the trace metal signatures at the sites (summarised by the centroids) are significantly different.</p>
</div>
</div>
<div id="dfa" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Discriminant Function Analysis (DFA)<a href="08-multivariate.html#dfa" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>DFA and MANOVA are mathematically identical, though DFA emphasises <em>classification</em> and <em>prediction</em>, and MANOVA tests hypotheses about group differences. MANOVA tests whether centroids across factor levels (groups) are significantly different, using the 1st discriminant function, a linear combination of all response variables. DFA uses all discriminant functions to calculate the <em>probability of correctly assigning observations to their pre-determined groups</em>, e.g. sites in the marine sediments example.</p>
<p>MANOVA is usually the first step in DFA because if the difference between group centroids is not significant then the discriminant functions will not be very useful for separating groups and therefore classifying observations. DFA is also used to <em>classify new observations into one of the groups</em>, calculating some measure of success of classification. DFA goes further than MANOVA in that it uses not only the 1st discriminant function but also additional discriminant functions to classify observations into groups.</p>
<p>In our marine sediments example, we already saw in the last section that the 1st discriminant function has the largest Eigenvalue and thus maximises the between group variance:within group variance ratio, hence separates the three sites best. We can now plot the discriminant functions using DFA:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="08-multivariate.html#cb199-1" tabindex="-1"></a><span class="co"># use linear discriminant function analysis which is available from the MASS package</span></span>
<span id="cb199-2"><a href="08-multivariate.html#cb199-2" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb199-3"><a href="08-multivariate.html#cb199-3" tabindex="-1"></a>sediments_dfa <span class="ot">&lt;-</span> <span class="fu">lda</span>(sediments_log[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], sediments_log<span class="sc">$</span>site)</span>
<span id="cb199-4"><a href="08-multivariate.html#cb199-4" tabindex="-1"></a><span class="co"># plot discriminant functions</span></span>
<span id="cb199-5"><a href="08-multivariate.html#cb199-5" tabindex="-1"></a><span class="fu">plot</span>(sediments_dfa, <span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>), <span class="at">xlab=</span><span class="st">&quot;DF1&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;DF2&quot;</span>)</span></code></pre></div>
<p><img src="qm4g_files/figure-html/unnamed-chunk-68-1.png" width="80%" /></p>
<p>We see that DF1 separates the three sites pretty well, better than the original variables in the scatterplot matrix in the previous section. DF2 adds little to this separation, as could already be seen in its comparably small Eigenvalue. The Eigenvalues of DF3 and DF4 are so small that they are considered zero and not displayed here.<a href="#fn34" class="footnote-ref" id="fnref34"><sup>34</sup></a></p>
<p>Looking at the Eigenvectors, the 4th original variable (Mn) contributes most to the 1st discriminant function - it is the best single discriminator - as could be seen already in the scatterplot matrix in the previous section:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="08-multivariate.html#cb200-1" tabindex="-1"></a><span class="co"># extract Eigenvectors</span></span>
<span id="cb200-2"><a href="08-multivariate.html#cb200-2" tabindex="-1"></a>sediments_dfa<span class="sc">$</span>scaling</span></code></pre></div>
<pre><code>##        LD1    LD2
## CU -0.5440  1.316
## PB  0.2147 -2.190
## NI -2.9056 -1.357
## MN -4.0423  1.244</code></pre>
<div id="classification" class="section level3 hasAnchor" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Classification<a href="08-multivariate.html#classification" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now we use the DFs to classify objects to (known) groups. For every measurement (object <span class="math inline">\(i\)</span>), three classification scores are calculated, one for every site (group <span class="math inline">\(j\)</span>). The classification scores are mathematically relate to the discriminant functions (Eigenvectors <span class="math inline">\(\mathbf{u_k}\)</span>). See <span class="citation">Quinn and Keough (<a href="#ref-quinn2002">2002</a>)</span> for details. The maximum classification score determines the group classification for every object. From this, for every object a probability of belonging to each of the groups is calculated:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="08-multivariate.html#cb202-1" tabindex="-1"></a><span class="co"># predict group membership</span></span>
<span id="cb202-2"><a href="08-multivariate.html#cb202-2" tabindex="-1"></a>sediments_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(sediments_dfa)</span>
<span id="cb202-3"><a href="08-multivariate.html#cb202-3" tabindex="-1"></a><span class="co"># extract probabilities</span></span>
<span id="cb202-4"><a href="08-multivariate.html#cb202-4" tabindex="-1"></a>sediments_pred<span class="sc">$</span>posterior</span></code></pre></div>
<pre><code>##          Delray  Seaspray  Woodside
##  [1,] 9.554e-01 4.461e-02 4.340e-09
##  [2,] 9.996e-01 4.344e-04 2.164e-12
##  [3,] 9.898e-01 1.018e-02 1.629e-09
##  [4,] 9.990e-01 9.697e-04 7.979e-11
##  [5,] 2.583e-02 9.736e-01 5.987e-04
##  [6,] 7.738e-02 9.226e-01 2.921e-07
##  [7,] 8.769e-04 9.965e-01 2.644e-03
##  [8,] 9.369e-05 9.055e-01 9.442e-02
##  [9,] 7.200e-13 3.429e-04 9.997e-01
## [10,] 1.500e-13 2.924e-06 1.000e+00
## [11,] 3.126e-07 2.704e-02 9.730e-01
## [12,] 3.719e-08 1.929e-03 9.981e-01</code></pre>
<p>We see that we can recover the original group membership this way: the first four samples have highest probability to be from Delray, the next four from Seaspray and the last four from Woodside. We can see this by constructing a contingency table:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="08-multivariate.html#cb204-1" tabindex="-1"></a><span class="co"># contingency table of prediction:group matches</span></span>
<span id="cb204-2"><a href="08-multivariate.html#cb204-2" tabindex="-1"></a><span class="fu">table</span>(sediments_pred<span class="sc">$</span>class, sediments_log<span class="sc">$</span>site)</span></code></pre></div>
<pre><code>##           
##            Delray Seaspray Woodside
##   Delray        4        0        0
##   Seaspray      0        4        0
##   Woodside      0        0        4</code></pre>
</div>
<div id="leave-one-out-cross-validation" class="section level3 hasAnchor" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Leave-one-out cross-validation<a href="08-multivariate.html#leave-one-out-cross-validation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Predicting the training data is no big deal. A more severe test of the classification approach is out-of-sample prediction (“validation”), which in small datasets we approximate by leave-one-out cross-validation (LOOCV). The algorithm is as follows:</p>
<ol style="list-style-type: decimal">
<li>For every measurement (object <span class="math inline">\(i\)</span>), do a DFA using only the remaining measurements (leaving object <span class="math inline">\(i\)</span> out)</li>
<li>Classify object <span class="math inline">\(i\)</span> with the corresponding classification equations</li>
<li>Repeat for all measurements</li>
</ol>
<p>LOOCV is implemented in the <code>lda()</code> function when we set the argument <code>CV=TRUE</code>:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="08-multivariate.html#cb206-1" tabindex="-1"></a><span class="co"># run DFA in LOOCV mode</span></span>
<span id="cb206-2"><a href="08-multivariate.html#cb206-2" tabindex="-1"></a>sediments_dfa2 <span class="ot">&lt;-</span> <span class="fu">lda</span>(sediments_log[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], sediments_log<span class="sc">$</span>site, <span class="at">CV=</span><span class="cn">TRUE</span>)</span>
<span id="cb206-3"><a href="08-multivariate.html#cb206-3" tabindex="-1"></a><span class="co"># extract probabilities</span></span>
<span id="cb206-4"><a href="08-multivariate.html#cb206-4" tabindex="-1"></a><span class="co"># we don&#39;t have to go via predict() in LOOCV mode</span></span>
<span id="cb206-5"><a href="08-multivariate.html#cb206-5" tabindex="-1"></a>sediments_dfa2<span class="sc">$</span>posterior</span></code></pre></div>
<pre><code>##          Delray  Seaspray  Woodside
##  [1,] 7.534e-01 2.466e-01 1.329e-07
##  [2,] 9.992e-01 7.610e-04 9.005e-12
##  [3,] 7.797e-04 9.992e-01 1.195e-05
##  [4,] 9.971e-01 2.903e-03 1.975e-09
##  [5,] 7.524e-02 9.223e-01 2.455e-03
##  [6,] 9.659e-01 3.411e-02 3.750e-14
##  [7,] 1.873e-03 9.912e-01 6.890e-03
##  [8,] 4.963e-05 8.439e-01 1.561e-01
##  [9,] 4.893e-17 7.520e-02 9.248e-01
## [10,] 1.486e-16 5.716e-08 1.000e+00
## [11,] 3.654e-06 7.148e-01 2.852e-01
## [12,] 1.000e+00 3.851e-09 6.456e-33</code></pre>
<p>Now the classification is less than perfect, as can be seen in the contingency table:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="08-multivariate.html#cb208-1" tabindex="-1"></a><span class="co"># contingency table of LOOCV prediction:group matches</span></span>
<span id="cb208-2"><a href="08-multivariate.html#cb208-2" tabindex="-1"></a><span class="fu">table</span>(sediments_dfa2<span class="sc">$</span>class, sediments_log<span class="sc">$</span>site)</span></code></pre></div>
<pre><code>##           
##            Delray Seaspray Woodside
##   Delray        3        1        1
##   Seaspray      1        3        1
##   Woodside      0        0        2</code></pre>
<p>A useful diagnostic, for this and other classification problems is the <strong>confusion matrix</strong> (Table <a href="08-multivariate.html#tab:confusion">7.1</a>).</p>
<table class=" lightable-paper lightable-hover" style='font-size: 12px; font-family: "Arial Narrow", arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;'>
<caption style="font-size: initial !important;">
<span id="tab:confusion">Table 7.1: </span>Confusion matrix. Type I error means incorrectly rejecting a true null hypothesis (detecting an effect that is not present). Type II error means failing to reject a false null hypothesis (failing to detect an effect that is present).
</caption>
<thead>
<tr>
<th style="text-align:left;">
Total population
</th>
<th style="text-align:left;">
Validation positive (1)
</th>
<th style="text-align:left;">
Validation negative (0)
</th>
<th style="text-align:left;">
Prevalence = sum of validation positives / total population
</th>
<th style="text-align:left;">
<ul>
<li></th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Prediction positive (1)
</td>
<td style="text-align:left;">
Sum of TRUE positives
</td>
<td style="text-align:left;">
Sum of FALSE positives (Type I error)
</td>
<td style="text-align:left;">
Precision = sum of TRUE positives / sum of prediction positives
</td>
<td style="text-align:left;">
False discovery rate = sum of FALSE positives / sum of prediction positives
</td>
</tr>
<tr>
<td style="text-align:left;">
Prediction negative (0)
</td>
<td style="text-align:left;">
Sum of FALSE negatives (Type II error)
</td>
<td style="text-align:left;">
Sum of TRUE negatives
</td>
<td style="text-align:left;">
False omission rate = sum of FALSE negatives / sum of prediction negatives
</td>
<td style="text-align:left;">
Negative predictive value = sum of TRUE negatives / sum of prediction negatives
</td>
</tr>
<tr>
<td style="text-align:left;">
Accuracy = (sum of TRUE positives + sum of TRUE negatives) / total population
</td>
<td style="text-align:left;">
TRUE positive rate (TPR), Sensitivity = sum of TRUE positives / sum of Validation positives
</td>
<td style="text-align:left;">
FALSE positive rate (FPR), Fall-out = sum of false positives / sum of validation negatives
</td>
<td style="text-align:left;">
Positive likelihood ratio (LR+) = TPR / FPR
</td>
<td style="text-align:left;">
Diagnostic odds ratio = LR+ / LR-
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
FALSE negative rate (FNR), Miss rate = sum of FALSE negatives / sum of validation positives
</td>
<td style="text-align:left;">
TRUE negative rate (TNR), Specificity = sum of TRUE negatives / sum of validation negatives
</td>
<td style="text-align:left;">
Negative likelihood ratio (LR-) = FNR / TNR
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table></li>
</ul>
<p>Filled in for the marine sediments example this is Table <a href="08-multivariate.html#tab:confusion2">7.2</a>.</p>
<table class=" lightable-paper lightable-hover" style='font-size: 12px; font-family: "Arial Narrow", arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;'>
<caption style="font-size: initial !important;">
<span id="tab:confusion2">Table 7.2: </span>Confusion matrix for marine sediments example.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Total population = 36
</th>
<th style="text-align:left;">
Validation positive (1)
</th>
<th style="text-align:left;">
Validation negative (0)
</th>
<th style="text-align:left;">
Prevalence = 1/3
</th>
<th style="text-align:left;">
<ul>
<li></th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Prediction positive (1)
</td>
<td style="text-align:left;">
8 TRUE positives
</td>
<td style="text-align:left;">
4 FALSE positives (Type I error)
</td>
<td style="text-align:left;">
Precision = 2/3
</td>
<td style="text-align:left;">
False discovery rate = 1/3
</td>
</tr>
<tr>
<td style="text-align:left;">
Prediction negative (0)
</td>
<td style="text-align:left;">
4 FALSE negatives (Type II error)
</td>
<td style="text-align:left;">
20 TRUE negatives
</td>
<td style="text-align:left;">
False omission rate = 1/6
</td>
<td style="text-align:left;">
Negative predictive value = 5/6
</td>
</tr>
<tr>
<td style="text-align:left;">
Accuracy = 7/9
</td>
<td style="text-align:left;">
TPR = 2/3
</td>
<td style="text-align:left;">
FPR = 1/6
</td>
<td style="text-align:left;">
LR+ = 4
</td>
<td style="text-align:left;">
Diagnostic odds ratio = 10
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
FNR = 1/3
</td>
<td style="text-align:left;">
TNR = 5/6
</td>
<td style="text-align:left;">
LR- = 2/5
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table></li>
</ul>

</div>
</div>
</div>
<h3>References<a href="10-refs.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-green1997" class="csl-entry">
Green, P. T. 1997. <span>“Red Crabs in Rain Forest on Christmas Island, Indian Ocean: Activity Patterns, Density and Biomass.”</span> <em>Journal of Tropical Ecology</em> 13 (1): 17–38. <a href="https://doi.org/10.1017/S0266467400010221">https://doi.org/10.1017/S0266467400010221</a>.
</div>
<div id="ref-haynes1995" class="csl-entry">
Haynes, D., D. Toohey, D. Clarke, and D. Marney. 1995. <span>“Temporal and Spatial Variation in Concentrations of Trace Metals in Coastal Sediments from the Ninety Mile Beach, Victoria, Australia.”</span> <em>Marine Pollution Bulletin</em> 30 (6): 414–18. <a href="https://doi.org/10.1016/0025-326X(95)00058-U">https://doi.org/10.1016/0025-326X(95)00058-U</a>.
</div>
<div id="ref-lovett2000" class="csl-entry">
Lovett, G. M., K. C. Weathers, and W. V. Sobczak. 2000. <span>“Nitrogen Saturation and Retention in Forested Watersheds of the Catskill Mountains, New York.”</span> <em>Ecological Applications</em> 10 (1): 73–84. <a href="https://doi.org/10.1890/1051-0761(2000)010[0073:NSARIF]2.0.CO;2">https://doi.org/10.1890/1051-0761(2000)010[0073:NSARIF]2.0.CO;2</a>.
</div>
<div id="ref-quinn2002" class="csl-entry">
Quinn, G. P., and M. J. Keough. 2002. <em>Experimental Design and Data Analysis for Biologists</em>. Cambridge: Cambridge University Press.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="25">
<li id="fn25"><p><a href="https://corneliussenf.com/" class="uri">https://corneliussenf.com/</a><a href="08-multivariate.html#fnref25" class="footnote-back">↩︎</a></p></li>
<li id="fn26"><p>It is called screeplot because it looks like the scree at the foot of a mountain.<a href="08-multivariate.html#fnref26" class="footnote-back">↩︎</a></p></li>
<li id="fn27"><p>The variance of a variable is of course the covariance between that variable and itself, e.g. <span class="math inline">\(var\left(y_1\right)=cov\left(y_1,y_1\right)\)</span>.<a href="08-multivariate.html#fnref27" class="footnote-back">↩︎</a></p></li>
<li id="fn28"><p>An example - though one that does not involve a covariance matrix! - is: <span class="math inline">\(\begin{pmatrix}2&amp;3\\2&amp;1\end{pmatrix}\cdot\begin{pmatrix}3\\2\end{pmatrix}=\begin{pmatrix}12\\8\end{pmatrix}=4\cdot\begin{pmatrix}3\\2\end{pmatrix}\)</span>.<a href="08-multivariate.html#fnref28" class="footnote-back">↩︎</a></p></li>
<li id="fn29"><p>You could try this yourself either way to see what difference it makes.<a href="08-multivariate.html#fnref29" class="footnote-back">↩︎</a></p></li>
<li id="fn30"><p>As we will see in Chapter <a href="08-multivariate.html#dfa">7.4</a>, the mathematics of MANOVA and DFA are identical.<a href="08-multivariate.html#fnref30" class="footnote-back">↩︎</a></p></li>
<li id="fn31"><p>Note, the total matrix is the covariance matrix without division by <span class="math inline">\(n-1\)</span>; the diagonals are the SSYs of the individual variables.<a href="08-multivariate.html#fnref31" class="footnote-back">↩︎</a></p></li>
<li id="fn32"><p>Note, the diagonals of the residual matrix are the SSEs of the individual variables.<a href="08-multivariate.html#fnref32" class="footnote-back">↩︎</a></p></li>
<li id="fn33"><p>By comparison, in PCA the Eigenanalysis is done on the covariance or correlation matrix.<a href="08-multivariate.html#fnref33" class="footnote-back">↩︎</a></p></li>
<li id="fn34"><p>In fact, the MANOVA estimated the Eigenvalues of DF3 and DF4 to be negative, which is a numerical error that happens at these very small numbers.<a href="08-multivariate.html#fnref34" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="07-glms.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="09-solutions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
